### ISSUE TITLE
FC after running shadowsocks-android

### ISSUE THREAD

**Issue by Cee** [shadowsocks/shadowsocks-android#1017]
### Problem 

> java.lang.RuntimeException: Unable to resume activity {com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

### Environment

* Android version: Nougat
* Device: Sony Z5 Dual
* Shadowsocks version: v3.3.1 (the latest version)
* Last version that did not exhibit the issue (if applicable): No

* Android System WebView is installed in my system.

### Logcat

```
12-22 17:01:31.630  6426  6426 E WebViewFactory: Chromium WebView package does not exist
12-22 17:01:31.630  6426  6426 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1246)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.util.am.a(:com.google.android.gms.DynamiteModulesA:418)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.util.ac.a(:com.google.android.gms.DynamiteModulesA:475)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.state.h.a(:com.google.android.gms.DynamiteModulesA:430)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.a.<init>(:com.google.android.gms.DynamiteModulesA:145)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.c.<init>(:com.google.android.gms.DynamiteModulesA:101)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.c.<init>(:com.google.android.gms.DynamiteModulesA:89)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.g.<init>(:com.google.android.gms.DynamiteModulesA:52)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.o.<init>(:com.google.android.gms.DynamiteModulesA:88)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.ChimeraAdManagerCreatorImpl.newAdManagerByType(:com.google.android.gms.DynamiteModulesA:69)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.client.an.onTransact(:com.google.android.gms.DynamiteModulesA:91)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.os.Binder.transact(Binder.java:499)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.client.ao.newAdManagerByType(:com.google.android.gms:170)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.AdManagerCreatorImpl.newAdManagerByType(:com.google.android.gms:92)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.internal.client.an.onTransact(:com.google.android.gms:91)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.os.Binder.transact(Binder.java:499)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeq$zza$zza.zza(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzdx.zza(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeg$1.zzeD(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeg$1.zzeE(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeg$zza.zzeM(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeg.zza(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzeg.zza(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzez.zzfe(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzez.zzfd(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.internal.zzez.zza(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.github.shadowsocks.Shadowsocks.updatePreferenceScreen(Shadowsocks.scala:407)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.github.shadowsocks.Shadowsocks.updateCurrentProfile(Shadowsocks.scala:364)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.github.shadowsocks.Shadowsocks.onResume(Shadowsocks.scala:387)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.Activity.performResume(Activity.java:6768)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:154)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
12-22 17:01:31.630  6426  6426 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by wongsyrone** [comment]
It seems it is caused by AdView.

**Comment by madeye** [comment]
It'd be an issue caused by outdated Google Play Service. Some suggestions:

1. Update your Google Play Service.
2. Install shadowsocks in Google Play Store.
3. Try some other ROMs.

**Comment by Cee** [comment]
@madeye @wongsyrone Thanks. I'll take all of these steps a try.

**Comment by Cee** [comment]
@wongsyrone Yes, it's caused by AdView in `Shadowsocks.scala` file.
