### ISSUE TITLE
Cannot install on Android x86

### ISSUE THREAD

**Issue by cthbleachbit** [shadowsocks/shadowsocks-android#1023]
Both Google Play and downloaded apk from github fail to install.

### Environment

* Android version: Android 6.0.1 x86_64
* Device: Surface Pro 3
* Shadowsocks version: version code "v3.31"
* Last version that did not exhibit the issue (if applicable): v3.27

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by madeye** [comment]
Tried on Android x86 emulator. Everything works well.

You may try to uninstall and reinstall the app.

**Comment by cthbleachbit** [comment]
Even a fresh install gives "App not installed".

**Comment by madeye** [comment]
Which ROM are you using? It looks no official Android ROM for Surface Pro.

**Comment by cthbleachbit** [comment]
It's a Android x86 build with customized linux kernel. 

Logcat message on adb
```
12-23 20:26:40.038 12947 12947 W InstallAppProgress: Replacing package:com.github.shadowsocks
12-23 20:26:40.043 12834 12845 I ABIPicker: selected abi x86(1) for com.github.shadowsocks
12-23 20:26:40.045  4452  4452 I Finsky  : [1] com.google.android.vending.verifier.PackageVerificationReceiver.onReceive(41): Verification requested, id = 14
12-23 20:26:40.079  1685  1704 I ActivityManager: Displayed com.android.packageinstaller/.InstallAppProgress: +45ms
12-23 20:26:40.099 12947 12964 D OpenGLRenderer: endAllStagingAnimators on 0x7f14be93f000 (RippleDrawable) with handle 0x7f14be7d7040
12-23 20:26:40.293  4452  4489 I Finsky  : [267] com.google.android.finsky.services.ForegroundCoordinator.a(104): Task 7 requested foreground
12-23 20:26:40.294  4452  4489 I Finsky  : [267] com.google.android.finsky.services.ForegroundCoordinator.a(116): Not entering foreground
12-23 20:26:40.429  4452  4452 I Finsky  : [1] com.google.android.vending.verifier.ar.a_(1793): Verification id=14 response=0
12-23 20:26:40.429  4452  4452 I Finsky  : [1] com.google.android.vending.verifier.ak.c(195): Verification complete: id=14, package_name=com.github.shadowsocks
12-23 20:26:40.429  4452  4452 I Finsky  : [1] com.google.android.vending.verifier.ak.g(17021): Verifying id=14, result=1
12-23 20:26:40.432 12834 12846 D DefContainer: Copying /storage/emulated/0/download/shadowsocks-nightly-3.3.1.apk to base.apk
12-23 20:26:40.447  1685  1708 I ABIPicker: selected abi x86(1) for com.github.shadowsocks
12-23 20:26:40.585  1685  1708 D NativeLibraryHelper: Library 'libsystem.so' is not page-aligned - will not be able to open it directly from apk.
12-23 20:26:40.585  1685  1708 E PackageManager: Error deriving application ABI
12-23 20:26:40.585  1685  1708 E PackageManager: com.android.server.pm.PackageManagerException: Error unpackaging native libs for app, errorCode=-2
12-23 20:26:40.585  1685  1708 E PackageManager: 	at com.android.server.pm.PackageManagerService.derivePackageAbi(PackageManagerService.java:7664)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12680)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10410)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at android.os.Handler.handleCallback(Handler.java:739)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at android.os.Looper.loop(Looper.java:148)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
12-23 20:26:40.585  1685  1708 E PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-23 20:26:40.585  1685  1708 W PackageManager: Error deriving application ABI
12-23 20:26:40.587  1685  1708 I art     : Starting a blocking GC Explicit
12-23 20:26:40.605  1685  1708 I art     : Explicit concurrent mark sweep GC freed 77201(4MB) AllocSpace objects, 35(1152KB) LOS objects, 33% free, 18MB/27MB, paused 231us total 18.454ms
12-23 20:26:40.616 12947 12947 D InstallAppProgress: Installation error code: -110
```

**Comment by wongsyrone** [comment]
> NativeLibraryHelper: Library 'libsystem.so' is not page-aligned - will not be able to open it directly from apk.

**Comment by cthbleachbit** [comment]
`libsystem.so` is at `<apk>/lib/x86/libsystem.so`

**Comment by cthbleachbit** [comment]
The app works on my Android phone normally though.

**Comment by wongsyrone** [comment]
looks similar to https://github.com/scala-android/sbt-android/issues/252#issuecomment-253543271

**Comment by madeye** [comment]
@Mygod A regression of sbt-android?

**Comment by Mygod** [comment]
That issue should have been fixed. It wouldn't have installed successfully
on the emulator otherwise.

**Comment by madeye** [comment]
OK. @cthbleachbit You may wait for the next release.

**Comment by Mygod** [comment]
Wait. Please be consistent with the information you supplied. Do you use x86_64 or x86?

**Comment by fishtown** [comment]
I faced same issue.
It works fine with my Android Tablet but hit same issue while using my phone(OPPO R9s).
More like platform related issue or can be workaround from app side?

reproduce as below:
1.Try to install shadowsocks from Google Play got -504 error 
​2.By adb install got "Failure [INSTALL_FAILED_INVALID_APK]" ​ It works fine on my Android M tablet. ​​Please help to share how to fix or bypass the security checking?

**Comment by cthbleachbit** [comment]
@fishtown is your tablet an x86 / x86_64 one?

I guess this is some sort of problem in kernel paging. Maybe there is something in kernel config that might fix this.
