### ISSUE TITLE
Cannot connect to internet with DNS Forwarding turned off

### ISSUE THREAD

**Issue by smilinger** [shadowsocks/shadowsocks-android#1185]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: 4.4.2
* Device: Huawei Honor 6 Plus
* Shadowsocks version: v4.1.3
* Last version that did not exhibit the issue (if applicable): version before #1156 maybe

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: aes-256-cfb
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Updated to the latest version

### What did you expect to see?

Be able to connect to internet with DNS Forwarding Off

### What did you see instead?

If DNS Forwarding is on everything is OK, otherwise cannot open any web site in browser with error DNS_PROBE_FINISHED_NXDOMAIN. I have tried change DNS servers and switch shadowsocks servers but it's not working.

I read the issue #1156, #1166 and code of f64014e, still don't understand the new mechanism, I don't know how should I set up to get it work.

**Comment by madeye** [comment]
> Android version: 4.4.2

Try Android 5.0 or above.

> If DNS Forwarding is on everything is OK, otherwise cannot open any web site in browser with error DNS_PROBE_FINISHED_NXDOMAIN. I have tried change DNS servers and switch shadowsocks servers but it's not working.

Please attach the logcat.

**Comment by smilinger** [comment]
Do you mean that the latest version is not compatible with Android 4.4.2?

**Comment by smilinger** [comment]
The most relevant error info from logcat might be this, when I activate the service:

`
Error when protect socket
java.io.IOException: Broken pipe
	at android.net.LocalSocketImpl.write_native(Native Method)
	at android.net.LocalSocketImpl.access$700(LocalSocketImpl.java:33)
	at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:147)
	at com.github.shadowsocks.ShadowsocksVpnThread.com$github$shadowsocks$ShadowsocksVpnThread$$run$body$1(ShadowsocksVpnThread.scala:98)
	at com.github.shadowsocks.ShadowsocksVpnThread$$anonfun$1.run(ShadowsocksVpnThread.scala:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
`

**Comment by madeye** [comment]
Try uninstall and reinstall the app.

**Comment by smilinger** [comment]
Already tried.

**Comment by smilinger** [comment]
Tried version 4.1.2, same problem. So maybe it's not f64014e, I will try the other versions.

**Comment by smilinger** [comment]
After some install and uninstall, I can confirm version 4.0.4 is OK, the problem started from version 4.1.0.

**Comment by Mygod** [comment]
The only major change in 4.1.0 is the addition of overture. But I don't see how that would cause this problem.

Also iirc, 4.1.0 is broken. Could you retry with 4.1.1 and/or later and confirm it's the same issue as https://github.com/shadowsocks/shadowsocks-android/issues/1185#issuecomment-290629253?

**Comment by Mygod** [comment]
Closing due to inactivity.

**Comment by smilinger** [comment]
Hi, sorry for late reply.

I tried all 4.1+ versions, they have the same error as https://github.com/shadowsocks/shadowsocks-android/issues/1185#issuecomment-290629253.

**Comment by Mygod** [comment]
@madeye Any thoughts?

**Comment by Mygod** [comment]
@madeye Any thoughts?

**Comment by madeye** [comment]
No idea. It looks a specific issue for some 4.4.2 AOSPs.

**Comment by Karius** [comment]
4.4.2，同样遇到了这个问题。

**Comment by madeye** [comment]
Could you try this APK? https://www.dropbox.com/s/ks6xk0l18p4or67/shadowsocks-nightly-4.1.7.apk

**Comment by Mygod** [comment]
Closing due to inactivity.

**Comment by Mygod** [comment]
Closing due to inactivity.

**Comment by smilinger** [comment]
@madeye Tried, not working either.

**Comment by madeye** [comment]
@smilinger Any logcat?

**Comment by madeye** [comment]
@smilinger Could you also try this? https://www.dropbox.com/s/hq253p1rtllnxq0/shadowsocks-nightly-4.1.7-experiment.apk

**Comment by madeye** [comment]
It turns out a bug related to Android 4.4's breaking dual stack support. Golang listens on `::0` by default which is a dual stack. However, Android 4.4's VPNService implementation cannot forward a IPv4 packet to the local dual stack address.

It's been fixed via 8f6357d and verified on a AOSP 4.4 device.

@smilinger Could you try this APK? https://www.dropbox.com/s/au3gavr8jadjhxh/shadowsocks-nightly-4.1.7-experiment-2.apk

**Comment by smilinger** [comment]
@madeye Still not working.

**Comment by smilinger** [comment]
Something worth noting:
Wechat seems to be working, I can receive messages, baidu tieba client seems working too, I can refresh for new messages, however images are not showing.
Sometimes I can open a few web sites in the browser, however I think that's just because the DNS cache. If I force close the browser and open again, no web site can open any more.

**Comment by madeye** [comment]
@smilinger Are you using this APK?  https://www.dropbox.com/s/au3gavr8jadjhxh/shadowsocks-nightly-4.1.7-experiment-2.apk

Maybe you can try uninstall and reinstall the app. I've tested it on a Huawei Honor with Android 4.4. It should work.

**Comment by smilinger** [comment]
@madeye Yes, I was using that apk. I also tried uninstall and reinstall.

Might be a specific case for my device only. Maybe I should reset my phone.

**Comment by madeye** [comment]
Let's try this APK. https://www.dropbox.com/s/w3i221l6cmakn4n/shadowsocks-nightly-4.1.7-experiment-3.apk

**Comment by smilinger** [comment]
@madeye Yes, this version is working perfectly. Nice work! Thank you.

**Comment by madeye** [comment]
Great!
