### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#1213]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Ubuntu 14.04 LTS

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
build as usual

### What did you expect to see?
Build successfully.

### What did you see instead?
`root@localhost:~/shadowsocks-android# ./make.bash 
[info] Loading project definition from /root/shadowsocks-android/project
[info] Set current project to shadowsocks-android (in build file:/root/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] Set current project to shadowsocks-android (in build file:/root/shadowsocks-android/)
[info] Get dependences for overture
[info] ~/shadowsocks-android/mobile/src/overture/src/github.com/shadowsocks/overture/main ~/shadowsocks-android
[info] Cross compile overture for arm
[info] Cross compile overture for arm64
[info] Cross compile overture for x86
[info] ~/shadowsocks-android
[info] Successfully build overture
[success] Total time: 92 s, completed Apr 14, 2017 8:08:30 AM
[info] Updating {file:/root/shadowsocks-android/}plugin...
[info] Resolving jline#jline;2.14.3 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.10/scala-library-2.11.10.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.11.10!scala-library.jar (11006ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.10/scala-compiler-2.11.10.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.11.10!scala-compiler.jar (26999ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.10/scala-reflect-2.11.10.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.10!scala-reflect.jar (8159ms)
[info] Done updating.
[info] Unpacking aar: preference-v14-25.3.1.aar to com.android.support-preference-v14-25.3.1
[info] Unpacking aar: support-v4-25.3.1.aar to com.android.support-support-v4-25.3.1
[info] Unpacking aar: support-compat-25.3.1.aar to com.android.support-support-compat-25.3.1
[info] Unpacking aar: support-media-compat-25.3.1.aar to com.android.support-support-media-compat-25.3.1
[info] Unpacking aar: support-core-utils-25.3.1.aar to com.android.support-support-core-utils-25.3.1
[info] Unpacking aar: support-core-ui-25.3.1.aar to com.android.support-support-core-ui-25.3.1
[info] Unpacking aar: support-fragment-25.3.1.aar to com.android.support-support-fragment-25.3.1
[info] Unpacking aar: appcompat-v7-25.3.1.aar to com.android.support-appcompat-v7-25.3.1
[info] Unpacking aar: support-vector-drawable-25.3.1.aar to com.android.support-support-vector-drawable-25.3.1
[info] Unpacking aar: animated-vector-drawable-25.3.1.aar to com.android.support-animated-vector-drawable-25.3.1
[info] Unpacking aar: recyclerview-v7-25.3.1.aar to com.android.support-recyclerview-v7-25.3.1
[info] Unpacking aar: preference-v7-25.3.1.aar to com.android.support-preference-v7-25.3.1
[info] Collecting resources
[info] Performing full resource merge
[info] QueuedCruncher is using /root/android/android-sdk/build-tools/25.0.2/aapt
[info] Processing resources
[info] QueuedCruncher is using /root/android/android-sdk/build-tools/25.0.2/aapt
[info] Compiling 15 Scala sources and 8 Java sources to /root/shadowsocks-android/plugin/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.10. Compiling...
[info]   Compilation completed in 20.829 s
[warn] [UnusedAttribute] src/main/res/layout/toolbar_light_dark.xml:8:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]     android:elevation="4dp"
[warn]     ~~~~~~~~~~~~~~~~~~~~~~~
[warn] lint found 1 warning
[info] Packaging /root/shadowsocks-android/plugin/target/android/intermediates/classes.jar ...
[info] Done packaging.
[info] Updating {file:/root/shadowsocks-android/}mobile...
[info] Resolving jline#jline;2.14.3 ...
[info] downloading https://repo1.maven.org/maven2/com/evernote/android-job/1.1.9/android-job-1.1.9.aar ...
[info] 	[SUCCESSFUL ] com.evernote#android-job;1.1.9!android-job.aar (1001ms)
[info] Done updating.
[info] Unpacking aar: cardview-v7-25.3.1.aar to com.android.support-cardview-v7-25.3.1
[info] Unpacking aar: customtabs-25.3.1.aar to com.android.support-customtabs-25.3.1
[info] Unpacking aar: gridlayout-v7-25.3.1.aar to com.android.support-gridlayout-v7-25.3.1
[info] Unpacking aar: android-job-1.1.9.aar to com.evernote-android-job-1.1.9
[info] Collecting resources
[info] Performing full resource merge
[info] QueuedCruncher is using /root/android/android-sdk/build-tools/25.0.2/aapt
[info] Processing resources
[info] QueuedCruncher is using /root/android/android-sdk/build-tools/25.0.2/aapt
[warn] warning: string 'misc_cat' has no default translation.
java.lang.RuntimeException: Error: more than one library with package name 'android.support.v14.preference'
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:994)
	at android.Resources$.aapt(resources.scala:380)
	at android.Tasks$$anonfun$70$$anonfun$apply$74.apply(tasks.scala:849)
	at android.Tasks$$anonfun$70$$anonfun$apply$74.apply(tasks.scala:845)
	at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:862)
	at android.Tasks$$anonfun$withCachedRes$1.apply(tasks.scala:860)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at android.Tasks$.withCachedRes(tasks.scala:863)
	at android.Tasks$$anonfun$70.apply(tasks.scala:845)
	at android.Tasks$$anonfun$70.apply(tasks.scala:836)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (mobile/android:rGenerator) Error: more than one library with package name 'android.support.v14.preference'
[error] Total time: 123 s, completed Apr 14, 2017 8:10:33 AM
`

**Comment by Mygod** [comment]
Do a clean first.
