### ISSUE TITLE
But ubuntu I can not compile successfully

### ISSUE THREAD

**Issue by jinshakx** [shadowsocks/shadowsocks-android#1249]
Can you help me?

root@p:~/android/shadowsocks-android# sbt clean go-build android:package-release
[info] Loading project definition from /root/android/shadowsocks-android/project
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] Set current project to shadowsocks-android (in build file:/root/android/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] ANDROID_HOME not set or invalid, using /root/.android/sbt/sdk
[info] Set current project to shadowsocks-android (in build file:/root/android/shadowsocks-android/)
[success] Total time: 0 s, completed 2017-5-10 15:38:17
[info] Make standalone toolchain for ARM arch
[error] mobile/src/overture/make.bash: 行 31: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Make standalone toolchain for ARM64 arch
[error] mobile/src/overture/make.bash: 行 37: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Make standalone toolchain for X86 arch
[error] mobile/src/overture/make.bash: 行 43: /root/java/android-ndk-r10e/build/tools/make_standalone_toolchain.py: There is no file or directory
[info] Build the custom go
[info] /android/shadowsocks-android/mobile/src/overture/go/src /android/shadowsocks-android
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] ERROR: Cannot find /root/go1.4/bin/go.
[error] Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
java.lang.RuntimeException: Native build script exit code: 255
at scala.sys.package$.error(package.scala:27)
at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:45)
at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:42)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
at sbt.std.Transform$$anon$4.work(System.scala:63)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.Execute.work(Execute.scala:237)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 0 s, completed 2017-5-10 15:38:18
root@p:/android/shadowsocks-android#
root@p:/android/shadowsocks-android#

**Comment by jinshakx** [comment]
GOROOT_BOOTSTRAP  I set it up

**Comment by Mygod** [comment]
Install go properly.

**Comment by jinshakx** [comment]
[info] Get dependences for overture
[info] ~/android/shadowsocks-android/mobile/src/overture/src/github.com/shadowsocks/overture/main ~/android/shadowsocks-android
[info] Cross compile overture for arm
[error] # runtime/cgo
[error] fork/exec /root/android/shadowsocks-android/mobile/src/overture/.deps/android-toolchain-19-arm/bin/arm-linux-androideabi-gcc: no such file or directory
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:45)
	at $ef3e8aa5c0bb0d165775$$anonfun$$sbtdef$1.apply(/root/android/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 20 s, completed 2017-5-10 16:45:43
root@p:~/android/shadowsocks-android#

**Comment by minenlink** [comment]
@jinshakx 
GOROOT_BOOTSTRAP 这个问题你解决了么？

**Comment by jinshakx** [comment]
Thank you  ！solving

**Comment by minenlink** [comment]
请问您是怎么解决的？我也碰到了类似的问题。能帮我看一下么？


[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] ERROR: Cannot find /home/mzx/go1.4/bin/go.
[error] Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:45)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 16 s, completed May 10, 2017 2:47:14 AM

**Comment by minenlink** [comment]
这是我的 go 环境配置
mzx@ubuntu:/Desktop/shadowsocks-android$ echo $GOROOT_BOOTSTRAP
/usr/local/go
mzx@ubuntu:/Desktop/shadowsocks-android$ go version
go version go1.4 linux/amd64

**Comment by minenlink** [comment]
@jinshakx

**Comment by jinshakx** [comment]
I am not very clear that I have this configuration is no problem? You change the authority to 777

**Comment by Mygod** [comment]
See README and .travis.yml for instructions.
