### ISSUE TITLE
Cannot run program "mobile/src/overture/make.bash":

### ISSUE THREAD

**Issue by minenlink** [shadowsocks/shadowsocks-android#1250]
hi,i build the project,but build error.
and i am sure ,the "mobile/src/overture/make.bash" file is exsists;
![image](https://cloud.githubusercontent.com/assets/25025688/25889195/7e7c9326-359b-11e7-90a9-007e744bd2ee.png)

what should i do?

mzx@ubuntu:~/Desktop/shadowsocks-android$ sbt clean go-build android:package-release
[info] Loading project definition from /home/mzx/Desktop/shadowsocks-android/project
[info] Set current project to shadowsocks-android (in build file:/home/mzx/Desktop/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] Set current project to shadowsocks-android (in build file:/home/mzx/Desktop/shadowsocks-android/)
[success] Total time: 157 s, completed May 10, 2017 1:03:58 AM
java.io.IOException: Cannot run program "mobile/src/overture/make.bash": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:43)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:43)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) java.io.IOException: Cannot run program "mobile/src/overture/make.bash": error=2, No such file or directory
[error] Total time: 34 s, completed May 10, 2017 1:04:33 AM

**Comment by Mygod** [comment]
Check execute permission.

**Comment by minenlink** [comment]
oh,thanks for you answer,it looks like ok now .
but another error...




[info] ~/Desktop/shadowsocks-android/mobile/src/overture/go/src ~/Desktop/shadowsocks-android
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] ERROR: Cannot find /home/mzx/go1.4/bin/go.
[error] Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:45)
	at $97e6ce38d1437582b177$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 102 s, completed May 10, 2017 1:50:54 AM
mzx@ubuntu:~/Desktop/shadowsocks-android$ echo $GOROOT_BOOTSTRAP
/usr/local/go
mzx@ubuntu:~/Desktop/shadowsocks-android$ go version
go version go1.4 linux/amd64

**Comment by minenlink** [comment]
@Mygod 
excuse,could you give me suggestion?

**Comment by whour** [comment]
> [error] ERROR: Cannot find /home/mzx/go1.4/bin/go

@minenlink 
```
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export GOROOT_BOOTSTRAP=$GOROOT
export PATH=$PATH:$GOPATH/bin
```
Configuration you .bashrc or .zshrc like this.
source .bashrc org source .zshrc .

**Comment by minenlink** [comment]
@whour thanks a lot.
i change my env is:
.bashrc 

export JAVA_HOME=/usr/local/java/jdk1.8.0_131
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH

export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export GOROOT_BOOTSTRAP=$GOROOT
export PATH=$PATH:$GOPATH/bin

export SBT_HOME=/usr/local/sbt
export PATH=${SBT_HOME}/bin:$PATH

export ANDROID_NDK_HOME=/usr/local/android/android-ndk-r14b
export PATH=$PATH:$ANDROID_NDK_HOME

export ANDROID_HOME=/usr/local/android/android-sdk-linux
export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH




then i run :


mzx@ubuntu:/home/mzx/Desktop/shadowsocks-android$ sbt clean go-build android:package-release
[info] Loading project definition from /home/mzx/Desktop/shadowsocks-android/project
[info] Updating {file:/home/mzx/Desktop/shadowsocks-android/project/}shadowsocks-android-build...
[info] Resolving com.android.tools.build#transform-api;2.0.0-deprecated-use-grad[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to shadowsocks-android (in build file:/home/mzx/Desktop/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] Set current project to shadowsocks-android (in build file:/home/mzx/Desktop/shadowsocks-android/)
[success] Total time: 0 s, completed May 10, 2017 7:20:39 AM
[info] Make standalone toolchain for ARM arch
[info] Make standalone toolchain for ARM64 arch
[info] Make standalone toolchain for X86 arch
[info] Build the custom go
[info] /home/mzx/Desktop/shadowsocks-android/mobile/src/overture/go/src /home/mzx/Desktop/shadowsocks-android
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] package ./cmd/dist
[error] 	imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $159f960991b8f88dd9a6$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:45)
	at $159f960991b8f88dd9a6$$anonfun$$sbtdef$1.apply(/home/mzx/Desktop/shadowsocks-android/mobile/build.sbt:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 159 s, completed May 10, 2017 7:23:18 AM




i have no idear about this.what should i do?

**Comment by minenlink** [comment]
@whour 

mzx@ubuntu:~/go$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build405857421=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by whour** [comment]
You should search this error first.
```
[error] package ./cmd/dist
[error] imports runtime: C source files not allowed when not using cgo or SWIG:
```

**Comment by Mygod** [comment]
See README and .travis.yml for instructions.
