### ISSUE TITLE
Android SDK command failed (1); see prior messages for details

### ISSUE THREAD

**Issue by minenlink** [shadowsocks/shadowsocks-android#1251]
when i do command:
sbt clean go-build android:package-release

[x86] Install        : libredsocks.so => /home/mzx/shadowsocks-android/mobile/target/android/intermediates/ndk/jni/x86/libredsocks.so
[x86] Install        : libss-local.so => /home/mzx/shadowsocks-android/mobile/target/android/intermediates/ndk/jni/x86/libss-local.so
[x86] Install        : libss-tunnel.so => /home/mzx/shadowsocks-android/mobile/target/android/intermediates/ndk/jni/x86/libss-tunnel.so
com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(LoggedOutput(sbt.MultiLogger@21112387)),List(),None,Buffer(-Xmx4g, -cp, /usr/local/android/android-sdk-linux/build-tools/25.0.3/lib/dx.jar),false,Map())
com.android.dx.command.Main --dex --num-threads=2 --output /home/mzx/shadowsocks-android/mobile/target/android/intermediates/dex /home/mzx/shadowsocks-android/mobile/target/android/intermediates/proguard/classes.proguard.jar
Android SDK command failed (1); see prior messages for details
             
	at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:210)
	at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:159)
	at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
	at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1422)
	at android.Dex$$anonfun$singleDex$1.apply(dex.scala:181)
	at android.Dex$$anonfun$singleDex$1.apply(dex.scala:151)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at android.Dex$.singleDex(dex.scala:186)
	at android.Dex$.dex(dex.scala:62)
	at android.Tasks$$anonfun$80.apply(tasks.scala:975)
	at android.Tasks$$anonfun$80.apply(tasks.scala:970)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(LoggedOutput(sbt.MultiLogger@21112387)),List(),None,Buffer(-Xmx4g, -cp, /usr/local/android/android-sdk-linux/build-tools/25.0.3/lib/dx.jar),false,Map())
com.android.dx.command.Main --dex --num-threads=2 --output /home/mzx/shadowsocks-android/mobile/target/android/intermediates/dex /home/mzx/shadowsocks-android/mobile/target/android/intermediates/proguard/classes.proguard.jar
Android SDK command failed (1); see prior messages for details
             
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.android.builder.core.DexByteCodeConverter.dexOutOfProcess(DexByteCodeConverter.java:206)
	at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:159)
	at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
	at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1422)
	at android.Dex$$anonfun$singleDex$1.apply(dex.scala:181)
	at android.Dex$$anonfun$singleDex$1.apply(dex.scala:151)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at android.Dex$.singleDex(dex.scala:186)
	at android.Dex$.dex(dex.scala:62)
	at android.Tasks$$anonfun$80.apply(tasks.scala:975)
	at android.Tasks$$anonfun$80.apply(tasks.scala:970)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(LoggedOutput(sbt.MultiLogger@21112387)),List(),None,Buffer(-Xmx4g, -cp, /usr/local/android/android-sdk-linux/build-tools/25.0.3/lib/dx.jar),false,Map())
com.android.dx.command.Main --dex --num-threads=2 --output /home/mzx/shadowsocks-android/mobile/target/android/intermediates/dex /home/mzx/shadowsocks-android/mobile/target/android/intermediates/proguard/classes.proguard.jar
Android SDK command failed (1); see prior messages for details
             
[error] (mobile/android:dex) com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: ForkOptions(None,Some(LoggedOutput(sbt.MultiLogger@21112387)),List(),None,Buffer(-Xmx4g, -cp, /usr/local/android/android-sdk-linux/build-tools/25.0.3/lib/dx.jar),false,Map())
[error] com.android.dx.command.Main --dex --num-threads=2 --output /home/mzx/shadowsocks-android/mobile/target/android/intermediates/dex /home/mzx/shadowsocks-android/mobile/target/android/intermediates/proguard/classes.proguard.jar
[error] Android SDK command failed (1); see prior messages for details
[error]              
[error] Total time: 399 s, completed May 10, 2017 9:51:39 PM

could anyone help me ?

**Comment by minenlink** [comment]
i restart my pc.
rebuild is ok.

**Comment by minenlink** [comment]
but i donot know why
