### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yhyandroid** [shadowsocks/shadowsocks-android#1291]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

*system mac ox 0.12.5 
*java version "1.8.0_101"
*sbt.version to: 0.13.1
*go version go1.8.3 darwin/amd64
* Shadowsocks version: *version code "v4.1.8" or commit ID "26b6853"*
* Last version that did not exhibit the issue (if applicable):

build  sbt clean go-build android:package-debug

error 

info] Build the custom go
[error] mobile/src/overture/make.bash: line 50: pushd: /Users/Yhyu/Downloads/shadowsocks-android-master/mobile/src/overture/go/src: No such file or directory
[error] mobile/src/overture/make.bash: line 4: ./make.bash: No such file or directory
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $b2574402542c936d2e61$$anonfun$$sbtdef$1.apply(/Users/Yhyu/Downloads/shadowsocks-android-master/mobile/build.sbt:60)
	at $b2574402542c936d2e61$$anonfun$$sbtdef$1.apply(/Users/Yhyu/Downloads/shadowsocks-android-master/mobile/build.sbt:57)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 12 s, completed 2017-7-5 11:16:11

How to solve it？

**Comment by madeye** [comment]
`git submodule update --init`
