### ISSUE TITLE
shadowsocks keep crashing

### ISSUE THREAD

**Issue by upwell** [shadowsocks/shadowsocks-android#1300]
Keep crashing after opening the app, no other operation is performed, just open the app. Only recovered after uninstalled the app, and install again. And after using for several days, the problem recur.

### Environment

* Android version: 7.1.1
* Device: HTC U11
* Shadowsocks version: 4.1.8 (Installed from Google Play)
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:SALSA20
* [ ] One-time authentication
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Just open the app

### What did you expect to see?
No crashing

### What did you see instead?
App crashed. From the adb log I can see the following message:
> 07-19 15:02:03.023 1812-3396/? D/PMS: releaseWL(fface4e): PARTIAL_WAKE_LOCK  wake:com.github.shadowsocks/com.evernote.android.job.JobRescheduleService 0x1 null 0x0
07-19 15:02:03.024 26123-26141/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[JobRescheduleService]
                                                   Process: com.github.shadowsocks:bg, PID: 26123
                                                   java.lang.IllegalArgumentException: No such service ComponentInfo{com.github.shadowsocks/com.evernote.android.job.v21.PlatformJobService}
                                                       at android.os.Parcel.readException(Parcel.java:1697)
                                                       at android.os.Parcel.readException(Parcel.java:1646)
                                                       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
                                                       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:70)
                                                       at com.evernote.android.job.v21.JobProxy21.schedule(JobProxy21.java:174)
                                                       at com.evernote.android.job.v21.JobProxy21.plantOneOff(JobProxy21.java:72)
                                                       at com.evernote.android.job.JobManager.schedule(JobManager.java:241)
                                                       at com.evernote.android.job.JobRequest.schedule(JobRequest.java:366)
                                                       at com.evernote.android.job.JobRescheduleService.onHandleIntent(JobRescheduleService.java:60)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:173)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
07-19 15:02:03.025 1812-2496/? E/ActivityManager: App crashed! Process: com.github.shadowsocks:bg

Just googled, got this information: https://github.com/evernote/android-job/issues/108

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1293#issuecomment-314159107

**Comment by madeye** [comment]
It looks background service is killed. Since you're using a HTC phone, please check the "cloud power saving" settings.

**Comment by upwell** [comment]
Seems not related to power saving setting. Shadowsocks is already in all whitelists of power related settings in my HTC phone.

**Comment by upwell** [comment]
I'm trying to build an apk with the following in proguard rules and see whether it works.
> -dontwarn com.evernote.android.job.gcm.**
-dontwarn com.evernote.android.job.util.GcmAvailableHelper

-keep public class com.evernote.android.job.v21.PlatformJobService
-keep public class com.evernote.android.job.v14.PlatformAlarmService
-keep public class com.evernote.android.job.v14.PlatformAlarmReceiver
-keep public class com.evernote.android.job.JobBootReceiver
-keep public class com.evernote.android.job.JobRescheduleService

**Comment by madeye** [comment]
@Mygod Any idea?

I thought previously we added this https://github.com/evernote/android-job/blob/master/library/proguard.txt to our build files?

**Comment by madeye** [comment]
One assumption is when GCM is connected, `com.evernote.android.job.gcm.PlatformGcmService` would be called, otherwise, `com.evernote.android.job.v21.PlatformJobService` is called.

However,  `com.evernote.android.job.v21.PlatformJobService` is proguarded.

**Comment by madeye** [comment]
I saw a lot of this kind of crashes in Analytics, but almost no logs from Play Console.

It makes sense now.

**Comment by upwell** [comment]
Using the new build for around a day, so far so good.

**Comment by upwell** [comment]
no crash by now. close this issue.

**Comment by madeye** [comment]
Cool! Thanks for the test.

**Comment by nipon101** [comment]
I'm using HTC U11 now, no crush when I lanch the app, but when I click the connect button, there is no response at all.

**Comment by Caij** [comment]
i'm a developer, I saw same crashes in Analytics (HTC )。 Are you solving it by adding proguard rules ?
