### ISSUE TITLE
 Cannot run program "mobile/src/overture/make.bash"

### ISSUE THREAD

**Issue by RICEYRQ** [shadowsocks/shadowsocks-android#1316]
首先执行git submodule update --init --recursive并没有问题。

最初编译时：
Invalid initial heap size: -Xms1g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

于是注释掉了.jvmopts里面的内容，内容如下：
```
#-Xms1g
#-Xmx3g
#-Xss2m
#-XX:+CMSClassUnloadingEnabled
#-XX:+UseConcMarkSweepGC
```

再次执行bt clean go-build android:package-release时：
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/rice/.sbt/0.13/staging/ffff8514a36c36d61d53/shadowsocks-android/project
[info] Set current project to shadowsocks-android (in build file:/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[info] Set current project to shadowsocks-android (in build file:/shadowsocks-android/)
[success] Total time: 0 s, completed 2017-7-29 21:21:03
java.io.IOException: Cannot run program "mobile/src/overture/make.bash": error=2, 没有那个文件或目录
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at $b64a02ffc6a8f14e7264$$anonfun$$sbtdef$1.apply(/home/rice/.sbt/0.13/staging/ffff8514a36c36d61d53/shadowsocks-android/mobile/build.sbt:65)
	at $b64a02ffc6a8f14e7264$$anonfun$$sbtdef$1.apply(/home/rice/.sbt/0.13/staging/ffff8514a36c36d61d53/shadowsocks-android/mobile/build.sbt:64)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, 没有那个文件或目录
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at $b64a02ffc6a8f14e7264$$anonfun$$sbtdef$1.apply(/home/rice/.sbt/0.13/staging/ffff8514a36c36d61d53/shadowsocks-android/mobile/build.sbt:65)
	at $b64a02ffc6a8f14e7264$$anonfun$$sbtdef$1.apply(/home/rice/.sbt/0.13/staging/ffff8514a36c36d61d53/shadowsocks-android/mobile/build.sbt:64)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/*:goBuild) java.io.IOException: Cannot run program "mobile/src/overture/make.bash": error=2, 没有那个文件或目录
[error] Total time: 0 s, completed 2017-7-29 21:21:03

以为是没有权限，于是赋予了权限
drwxrwxrwx 4 root root 4096 7月  22 18:54 .
drwxr-xr-x 4 root root 4096 7月  22 17:17 ..
drwxr-xr-x 9 root root 4096 7月  22 19:14 go
-rwxrwxrwx 1 root root 2712 7月  22 17:17 make.bash
drwxr-xr-x 3 root root 4096 7月  22 17:17 src

但是再次编译仍然不行，报错依然是：
[error] (mobile/*:goBuild) java.io.IOException: Cannot run program "mobile/src/overture/make.bash": error=2, 没有那个文件或目录
[error] Total time: 0 s, completed 2017-7-29 21:23:17

环境变量：
export ANDROID_NDK_HOME=/home/rice/android-ndk-r14b
export ANDROID_HOME=/home/rice/android-sdk-linux
export PATH=$ANDROID_NDK_HOME:$PATH
export GOROOT=/home/rice/go
export GOROOT_BOOTSTRAP=/home/rice/go
export GOBIN=$GOROOT/bin
export GOPATH=/usr/local
export PATH=$PATH:$GOPATH:$GOBIN:$GOPATH
export JAVA_HOME=/home/rice/jdk1.8.0_141
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
export PATH=$JAVA_HOME/bin:$PATH
export PATH=/home/rice/sbt/bin:$PATH
export PATH=/home/rice/android-sdk-linux/tools:$PATH
export PATH=/home/rice/android-sdk-linux/platform-tools:$PATH
export PATH=/home/rice/android-sdk-linux/build-tools:$PATH

**Comment by Mygod** [comment]
Clone this repo under a file system with proper permission support.

**Comment by jokerpan** [comment]
@Mygod 请问一下，这是说不能直接复制已经clone好的项目进行编译是吗？

**Comment by madeye** [comment]
The best practice is using `git clone` to get the code.

**Comment by ncc0706** [comment]
@Mygod 我是windows操作系统可以编译吗
