### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by RICEYRQ** [shadowsocks/shadowsocks-android#1321]
环境变量什么的肯定是没有问题的，本来是能正确编译的，后来我试着改了一点代码，在左侧菜单里面加了几项，结果依然能编译，但是最后会报错。

最后报错信息：
java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at android.Proguard$.runProguard(proguard.scala:210)
	at android.Proguard$.proguard(proguard.scala:164)
	at android.Tasks$$anonfun$86.apply(tasks.scala:1062)
	at android.Tasks$$anonfun$86.apply(tasks.scala:1060)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (mobile/android:proguard) java.io.IOException: Please correct the above warnings first.
[error] Total time: 82 s, completed 2017-8-1 22:42:42

warning 和 error 如下：

[warn] [UnusedAttribute] src/main/res/layout/toolbar_light_dark.xml:8:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]     android:elevation="4dp"
[warn]     ~~~~~~~~~~~~~~~~~~~~~~~
[warn] lint found 1 warning

[warn] warning: string 'custom_service' has no default translation.
[warn] warning: string 'login' has no default translation.
[warn] warning: string 'misc_cat' has no default translation.
[warn] warning: string 'server_list' has no default translation.
[info] Rebuilding all classes because R.java has changed
[info] Compiling 61 Scala sources and 28 Java sources to /shadowsocks-android/mobile/target/scala-2.11/classes...
[warn] there were 7 deprecation warnings; re-run with -deprecation for details
[warn] there was one feature warning; re-run with -feature for details
[warn] two warnings found
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/DialogFragment.class:Call requires API level 23 (current min is 19): android.app.DialogFragment#onAttach
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/QuickToggleShortcut.class:Class requires API level 25 (current min is 19): android.content.pm.ShortcutManager
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ScannerActivity.class:Class requires API level 25 (current min is 19): android.content.pm.ShortcutManager
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksApplication.class:Call requires API level 21 (current min is 19): java.util.Locale#getScript
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksApplication.class:Call requires API level 21 (current min is 19): java.util.Locale#toLanguageTag
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19): android.net.VpnService.Builder#addAllowedApplication
[error] [NewApi] target/scala-2.11/classes/com/github/shadowsocks/ShadowsocksVpnService$$anonfun$startVpn$2.class:Call requires API level 21 (current min is 19): android.net.VpnService.Builder#addDisallowedApplication
[warn] [UnusedAttribute] src/main/AndroidManifest.xml:27:Attribute banner is only used in API level 21 and higher (current min is 19)
[warn]             android:banner="@drawable/ic_start_connected">
[warn]             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/layout/layout_apps.xml:13:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]                 android:elevation="1dp"
[warn]                 ~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/layout/layout_main.xml:13:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]                   android:elevation="4dp"
[warn]                   ~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/layout/layout_main.xml:74:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]                                                    android:elevation="6dp"
[warn]                                                    ~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/layout/layout_tasker.xml:9:Attribute elevation is only used in API level 21 and higher (current min is 19)
[warn]                  android:elevation="1dp"
[warn]                  ~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/xml/shortcuts.xml:3:Attribute shortcutId is only used in API level 25 and higher (current min is 19)
[warn]     <shortcut android:shortcutId="toggle"
[warn]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/xml/shortcuts.xml:5:Attribute shortcutShortLabel is only used in API level 25 and higher (current min is 19)
[warn]               android:shortcutShortLabel="@string/quick_toggle"
[warn]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[warn] [UnusedAttribute] src/main/res/xml/shortcuts.xml:6:Attribute shortcutLongLabel is only used in API level 25 and higher (current min is 19)
[warn]               android:shortcutLongLabel="@string/quick_toggle">
[warn]               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[error] lint found 7 errors, 8 warnings

[warn] warning: string 'custom_service' has no default translation.
[warn] warning: string 'login' has no default translation.
[warn] warning: string 'misc_cat' has no default translation.
[warn] warning: string 'server_list' has no default translation.

感觉上报错的文件我都没有动过，为什么会出现api过低这种问题。。。。

**Comment by madeye** [comment]
Make sure you didn't touch AndroidManifest.xml and build.sbt

**Comment by hhhaiai** [comment]
我也是编译不过.遇到两个问题
[电脑环境]
       macosx 10.12.6. 
       go1.7.3
       android 全版本SDK均有
       java 1.8.0_111
[问题]
      1.字符转换问题,这个不知道是环境问题,还是脚本问题
      2.一直提示 gopath未设置. 已经设置 
              >sanbo(11:30:54) [~/code/shadowsocks-android]$ echo $GOPATH 
              >/usr/local/Cellar/go/1.7.3

```
sanbo(11:27:16) [~/code/shadowsocks-android]$ git submodule update --init --recursive
sanbo(11:27:30) [~/code/shadowsocks-android]$ sbt clean go-build android:package-release
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
	at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
	at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
	at sbt.StandardMain$.initialState(Main.scala:125)
	at sbt.xMain.run(Main.scala:34)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)

[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /Users/sanbo/code/shadowsocks-android/project
[warn] Observed package id 'add-ons;addon-google_apis-google-16' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16')
[warn] Already observed package id 'add-ons;addon-google_apis-google-16' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-17' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17')
[warn] Already observed package id 'add-ons;addon-google_apis-google-17' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-18' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18')
[warn] Already observed package id 'add-ons;addon-google_apis-google-18' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19')
[warn] Already observed package id 'add-ons;addon-google_apis-google-19' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-21' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21')
[warn] Already observed package id 'add-ons;addon-google_apis-google-21' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22')
[warn] Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23')
[warn] Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-16' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16')
[warn] Already observed package id 'add-ons;addon-google_apis-google-16' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-17' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17')
[warn] Already observed package id 'add-ons;addon-google_apis-google-17' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-18' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18')
[warn] Already observed package id 'add-ons;addon-google_apis-google-18' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19')
[warn] Already observed package id 'add-ons;addon-google_apis-google-19' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-21' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21')
[warn] Already observed package id 'add-ons;addon-google_apis-google-21' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22')
[warn] Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23')
[warn] Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1'
[info] Set current project to shadowsocks-android (in build file:/Users/sanbo/code/shadowsocks-android/)
[info] Adding android subproject dependency rules for: mobile
[warn] Observed package id 'add-ons;addon-google_apis-google-16' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16')
[warn] Already observed package id 'add-ons;addon-google_apis-google-16' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-17' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17')
[warn] Already observed package id 'add-ons;addon-google_apis-google-17' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-18' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18')
[warn] Already observed package id 'add-ons;addon-google_apis-google-18' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19')
[warn] Already observed package id 'add-ons;addon-google_apis-google-19' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-21' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21')
[warn] Already observed package id 'add-ons;addon-google_apis-google-21' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22')
[warn] Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23')
[warn] Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1'
[info] Set current project to shadowsocks-android (in build file:/Users/sanbo/code/shadowsocks-android/)
[success] Total time: 10 s, completed 2017-8-7 11:27:56
[info] Build the custom go
[info] ~/code/shadowsocks-android/mobile/src/overture/go/src ~/code/shadowsocks-android
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] warning: GOPATH set to GOROOT (/usr/local/Cellar/go/1.7.3) has no effect
[error] cmd/dist/build.go:8:2: cannot find package "bytes" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/bytes (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:9:2: cannot find package "encoding/json" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/encoding/json (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:9:2: cannot find package "errors" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/errors (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:10:2: cannot find package "flag" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/flag (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:11:2: cannot find package "fmt" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/fmt (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/util.go:10:2: cannot find package "io" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/io (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:12:2: cannot find package "io/ioutil" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/io/ioutil (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:13:2: cannot find package "log" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/log (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:12:2: cannot find package "os" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/os (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:13:2: cannot find package "os/exec" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/os/exec (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:14:2: cannot find package "path/filepath" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/path/filepath (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:17:2: cannot find package "regexp" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/regexp (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/util.go:15:2: cannot find package "runtime" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/runtime (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:15:2: cannot find package "sort" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/sort (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/main.go:11:2: cannot find package "strconv" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/strconv (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:16:2: cannot find package "strings" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/strings (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:17:2: cannot find package "sync" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/sync (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:21:2: cannot find package "time" in any of:
[error] 	/usr/local/Cellar/go/1.7.3/src/time (from $GOROOT)
[error] 	($GOPATH not set)
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $57efec5ddb03dce6c340$$anonfun$$sbtdef$1.apply(/Users/sanbo/code/shadowsocks-android/mobile/build.sbt:67)
	at $57efec5ddb03dce6c340$$anonfun$$sbtdef$1.apply(/Users/sanbo/code/shadowsocks-android/mobile/build.sbt:64)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 1 s, completed 2017-8-7 11:27:57
```

**Comment by Mygod** [comment]
Just look at your error message and fix it yourself (or remove everything and restart completely). It seems to me that you have misconfigured a lot of stuff.

**Comment by HarrisonShen** [comment]
Can you add my qq ，my qq is 355969727，i dont know how to build it,I hope you help me
