### ISSUE TITLE
Unsatisfied Link Error

### ISSUE THREAD

**Issue by prowsandy** [shadowsocks/shadowsocks-android#1326]
Process: com.lvwind.shadowsocks, PID: 25185
                                                                        java.lang.UnsatisfiedLinkError: Couldn't load system from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.lvwind.shadowsocks-1.apk,libraryPath=/data/app-lib/com.lvwind.shadowsocks-1]: findLibrary returned null
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                            at java.lang.System.loadLibrary(System.java:526)
                                                                            at com.lvwind.shadowsocks.System.<clinit>(System.java:8)
                                                                            at com.lvwind.shadowsocks.utils.AssetsUtil$1.run(AssetsUtil.java:23)

Hello, I got this error when I compile the project. Any wrong action I did? or something is missing? Thanks

**Comment by madeye** [comment]
According to your logs, it looks an issue of the downstream fork. Please report to `com.lvwind.shadowsocks` instead.
