### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by W-quan** [shadowsocks/shadowsocks-android#1387]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.1.1*
* Device: *nubia z7 mini*
* Shadowsocks version: *version code "v4.1.8"*

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?

Scan QR

### What did you expect to see?

Open camera and Scan QR.

### What did you see instead?

Crash

## Log

```
 ActivityManager: Activity Manager Crash
09-25 10:17:08.419 22797 26410 E ActivityManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.pm.PackageManagerService.isComponentProtected(PackageManagerService.java:20902)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.am.ActivityStarter.shouldExcludeFromRecents(ActivityStarter.java:2197)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:830)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4572)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4540)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:166)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2987)
09-25 10:17:08.419 22797 26410 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
09-25 10:17:08.429 16786 16786 E InputEventReceiver: Exception dispatching input event.
09-25 10:17:08.429 16786 16786 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.os.Parcel.readException(Parcel.java:1690)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.os.Parcel.readException(Parcel.java:1637)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3115)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1641)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Activity.startActivityForResult(Activity.java:4879)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Activity.startActivityFromFragment(Activity.java:4864)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7145)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Fragment.startActivityForResult(Fragment.java:1150)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.app.Fragment.startActivityForResult(Fragment.java:1139)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at com.github.shadowsocks.ProfilesFragment.onMenuItemClick(ProfilesFragment.scala:355)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:88)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4066)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3825)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:10024)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2277)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:10244)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-25 10:17:08.453 16786 16786 E MessageQueue-JNI: 	at android.os.MessageQueue.next(Messag
```

**Comment by Mygod** [comment]
Seems like something else went wrong before this. Please attach full log.

**Comment by W-quan** [comment]
```
 E AndroidRuntime: FATAL EXCEPTION: main
09-25 14:16:22.078 12629 12629 E AndroidRuntime: Process: com.github.shadowsocks, PID: 12629
09-25 14:16:22.078 12629 12629 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1690)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3115)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1641)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4879)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Activity.startActivityFromFragment(Activity.java:4864)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7145)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Fragment.startActivityForResult(Fragment.java:1150)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.Fragment.startActivityForResult(Fragment.java:1139)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at com.github.shadowsocks.ProfilesFragment.onMenuItemClick(ProfilesFragment.scala:355)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:88)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
09-25 14:16:22.078 12629 12629 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

```


I think that is enough.

**Comment by Mygod** [comment]
No.

**Comment by ylivan09** [comment]
Environment

Android version: LineageOS 7.1.2
Device: Redmi Note 3 ( keozo )
Shadowsocks version: version code "v4.2.5"

What did you do?

click Scan QR code icon

What did you expect to see?

Open camera and Scan QR.

What did you see instead?

it says: shadowsocks has stopped.

**Comment by Mygod** [comment]
The FULL log please.

**Comment by Mygod** [comment]
Closing due to inactivity.
