### ISSUE TITLE
Can not start to connect to server

### ISSUE THREAD

**Issue by pokedo0** [shadowsocks/shadowsocks-android#1394]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *7.1.1"
* Device: *Samsung note8*
* Shadowsocks version: *version code "v4.2.5"

### Configuration

_Put an `x` inside the [ ] that applies._

* [x ] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: rc4-md5
* [ ] One-time authentication
* Route
  * [ x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [x ] TCP Fast Open
* [ ] NAT mode

### What did you do?
按下启动按钮，却无法启动连接。
Press the Connection button, but nothing happened.
Only Reboot device can i connect to server normally.
Here is record: https://www.youtube.com/watch?v=tGWyspak1Hs

### What did you expect to see?
可以正常连接。
Start connection normally

### What did you see instead?
无法启动连接。
Can not start connection.

**Comment by madeye** [comment]
Double check Shadowsocks is in the white list of your ROM's background killer or battery saver.

**Comment by pokedo0** [comment]
仔细检查了 battery saver 选项，并且卸载了黑域和绿色守护，使用几天后，并没有再出现以上情况。
如再出现类似情况会继续提issue。

**Comment by skyred** [comment]
I reproduce this problem on a fresh new Essential PH1 phone, the error message is below when I click the "connect" FAB for the first time

````
10-17 23:35:47.032 1500-2768/? W/AppOps: Bad call: specified package com.github.shadowsocks under uid 10042 but it is really 10114
                                         java.lang.RuntimeException: here
                                             at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1302)
                                             at com.android.server.AppOpsService.noteOperationUnchecked(AppOpsService.java:1043)
                                             at com.android.server.AppOpsService.noteOperation(AppOpsService.java:1036)
                                             at android.app.AppOpsManager.noteOpNoThrow(AppOpsManager.java:1800)
                                             at com.android.server.connectivity.Vpn.isVpnUserPreConsented(Vpn.java:560)
                                             at com.android.server.connectivity.Vpn.prepare(Vpn.java:440)
                                             at com.android.server.ConnectivityService.prepareVpn(ConnectivityService.java:3497)
                                             at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:544)
                                             at android.os.Binder.execTransact(Binder.java:565)
10-17 23:35:47.037 920-1259/? D/audio_hw_primary: start_output_stream: exit
10-17 23:35:47.085 1500-1557/? I/ActivityManager: Displayed com.android.vpndialogs/.ConfirmDialog: +62ms
````
If I click the "connect" FAB again, I got this info, and there is still no connection:

```
10-17 23:42:44.621 920-1259/? D/audio_hw_primary: start_output_stream: enter: stream(0xef35a780)usecase(1: low-latency-playback) devices(0x2)
10-17 23:42:44.623 920-1259/? D/audio_hw_primary: select_devices for use case (low-latency-playback)
10-17 23:42:44.623 920-1259/? D/audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
10-17 23:42:44.623 920-1259/? I/msm8974_platform: platform_check_and_set_codec_backend_cfg:becf: afe: bitwidth 16, samplerate 48000 channels 2, backend_idx 0 usecase = 1 device (speaker)
10-17 23:42:44.623 920-1259/? D/msm8974_platform: platform_split_snd_device: snd_device(2) new_snd_devices (speaker)
10-17 23:42:44.623 920-1259/? I/msm8974_platform: platform_check_and_set_codec_backend_cfg: new_snd_devices[0] is 2
10-17 23:42:44.623 920-1259/? I/msm8974_platform: platform_check_codec_backend_cfg:becf: afe: bitwidth 16, samplerate 48000 channels 2, backend_idx 0 usecase = 1 device (speaker)
10-17 23:42:44.623 920-1259/? D/msm8974_platform: platform_check_codec_backend_cfg:becf: afe: playback on codec device not supporting native playback set default Sample Rate(48k)
10-17 23:42:44.623 920-1259/? I/msm8974_platform: platform_check_codec_backend_cfg:becf: afe: Codec selected backend: 0 updated bit width: 16 and sample rate: 48000
10-17 23:42:44.623 920-1259/? D/audio_hw_primary: check_usecases_codec_backend:becf: force routing 0
10-17 23:42:44.623 920-1259/? E/msm8974_platform: platform_check_backends_match: Invalid snd_device = 
10-17 23:42:44.624 920-1259/? D/audio_hw_primary: check_usecases_codec_backend:becf: (44) check_usecases curr device: speaker, usecase device: backends match 0
10-17 23:42:44.624 920-1259/? D/audio_hw_primary: check_usecases_codec_backend:becf: check_usecases num.of Usecases to switch 0
10-17 23:42:44.624 920-1259/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
10-17 23:42:44.624 920-1259/? D/msm8974_platform: platform_split_snd_device: snd_device(2) new_snd_devices (speaker)
10-17 23:42:44.624 920-1259/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
10-17 23:42:44.624 920-1259/? I/soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1, with Raise=0
10-17 23:42:44.624 920-1259/? D/audio_hw_primary: setSpeakerProfile: set speaker Profile, profile type=0
10-17 23:42:44.645 920-1259/? D/audio_hw_primary: enable_audio_route: change smartamp to music mode
10-17 23:42:44.645 920-1259/? D/soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 3, with Raise=0
10-17 23:42:44.645 920-1259/? D/audio_hw_utils: audio_extn_utils_send_app_type_cfg: usecase->out_snd_device speaker
10-17 23:42:44.645 920-1259/? D/msm8974_platform: platform_split_snd_device: snd_device(2) new_snd_devices (speaker)
10-17 23:42:44.645 920-1259/? I/audio_hw_utils: send_app_type_cfg_for_device PLAYBACK app_type 69937, acdb_dev_id 15, sample_rate 48000, snd_device_be_idx 39
10-17 23:42:44.646 920-1259/? D/msm8974_platform: platform_split_snd_device: snd_device(2) new_snd_devices (speaker)
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path = 0, app id = 0x11131, sample rate = 48000
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_asm_topology
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_adm_topology
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_audtable
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_audvoltable
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_audstrmtable
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 16
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_afe_topology
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 15, Topology Id 1025e
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_afe_cal
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 15 path = 0
10-17 23:42:44.646 920-1259/? D/ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
10-17 23:42:44.646 920-1259/? D/audio_hw_primary: enable_audio_route: apply mixer and update path: low-latency-playback speaker
10-17 23:42:44.646 920-1259/? D/audio_hw_primary: select_devices: done
10-17 23:42:44.648 920-1259/? D/msm8974_platform: platform_set_channel_map mixer_ctl_name:Playback Channel Map13
10-17 23:42:44.648 920-1259/? D/msm8974_platform: platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
10-17 23:42:44.668 920-1259/? D/audio_hw_primary: start_output_stream: exit
10-17 23:42:44.668 631-3150/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
                                                      
                                                      --------- beginning of system
```  

On this new phone, I didn't install any third-party app like mentioned in https://github.com/shadowsocks/shadowsocks-android/issues/1394#issuecomment-335796631

What else can I do to continue debugging?
