### ISSUE TITLE
Which go edition does it use?compile it on go 1.9.1 official get error "no such tool compile"

### ISSUE THREAD

**Issue by wenewzhang** [shadowsocks/shadowsocks-android#1420]
Which go edition does it use?compile it on go 1.9.1 official get error "no such tool compile"
i suppose that need install go of shadowsocks,am i right?

Regards

### Environment
OS X with go 1.9.1 official
# Command
sbt clean go-build android:package-release

#Error Messages

[error] go tool: no such tool "compile"
[info] ~/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/src/github.com/shadowsocks/overture/main ~/Documents/Shadowsocks/shadowsocks-android
[error] mobile/src/overture/make.bash: line 63: godep: command not found
[info] Cross compile overture for arm
[error] log_android.go:31:2: cannot find package "github.com/Sirupsen/logrus" in any of:
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/go/src/github.com/Sirupsen/logrus (from $GOROOT)
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/src/github.com/Sirupsen/logrus (from $GOPATH)
[error] ../core/cache/cache.go:15:2: cannot find package "github.com/miekg/dns" in any of:
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/go/src/github.com/miekg/dns (from $GOROOT)
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/src/github.com/miekg/dns (from $GOPATH)
[error] ../core/outbound/client.go:14:2: cannot find package "golang.org/x/net/proxy" in any of:
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/go/src/golang.org/x/net/proxy (from $GOROOT)
[error] 	/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/src/overture/src/golang.org/x/net/proxy (from $GOPATH)
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $9be8c5fa599d6fed6a55$$anonfun$$sbtdef$1.apply(/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/build.sbt:67)
	at $9be8c5fa599d6fed6a55$$anonfun$$sbtdef$1.apply(/Users/jackma/Documents/Shadowsocks/shadowsocks-android/mobile/build.sbt:64)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 4 s, completed Oct 19, 2017 3:19:45 PM

**Comment by madeye** [comment]
I don't think it's an issue of our build script.

Consult travis-ci to debug your build environment: https://travis-ci.org/shadowsocks/shadowsocks-android

**Comment by Mygod** [comment]
Try to compile other go projects. I think your build system is corrupted.

**Comment by wenewzhang** [comment]
Thank for your guys reply,
reinstall the go 1.9.1 by package instead of brew-go to fix this,
and now,i got the new error message, i suppose this project dependent on the special Go-edition,
am i right?
would i compile it under the official go 1.9.1?

Best Regards

error msg: 
[error] # github.com/shadowsocks/overture/main
[error] ./utils_android.go:9:30: undefined: net.DialCallback
[error] ./utils_android.go:10:2: undefined: net.Callback
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)

**Comment by Mygod** [comment]
You need to build our modified go and build overture with the modified go.
