### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by hhhaiai** [shadowsocks/shadowsocks-android#1465]
### Environment
mac 10.12.6

### ErrorLog

```
[warn] Run 'evicted' to see detailed eviction warnings
[warn] Observed package id 'add-ons;addon-google_apis-google-16' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16')
[warn] Already observed package id 'add-ons;addon-google_apis-google-16' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-17' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17')
[warn] Already observed package id 'add-ons;addon-google_apis-google-17' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-18' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18')
[warn] Already observed package id 'add-ons;addon-google_apis-google-18' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19')
[warn] Already observed package id 'add-ons;addon-google_apis-google-19' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-21' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21')
[warn] Already observed package id 'add-ons;addon-google_apis-google-21' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22')
[warn] Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23')
[warn] Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-16' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16')
[warn] Already observed package id 'add-ons;addon-google_apis-google-16' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-16-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-17' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17')
[warn] Already observed package id 'add-ons;addon-google_apis-google-17' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-17-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-18' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18')
[warn] Already observed package id 'add-ons;addon-google_apis-google-18' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-18-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19')
[warn] Already observed package id 'add-ons;addon-google_apis-google-19' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-19-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-21' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21')
[warn] Already observed package id 'add-ons;addon-google_apis-google-21' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-21-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-22' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22')
[warn] Already observed package id 'add-ons;addon-google_apis-google-22' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-22-1'
[warn] Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23')
[warn] Already observed package id 'add-ons;addon-google_apis-google-23' in '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23'. Skipping duplicate at '/Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-23-1'
[info] Set current project to shadowsocks-android (in build file:/Users/sanbo/code/ss/shadowsocks-android/)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 



if click i then 

java.lang.RuntimeException: Session not initialized.
	at scala.sys.package$.error(package.scala:27)
	at sbt.Project$$anonfun$getOrError$1.apply(Project.scala:315)
	at sbt.Project$$anonfun$getOrError$1.apply(Project.scala:315)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.Project$.getOrError(Project.scala:315)
	at sbt.Project$.session(Project.scala:317)
	at sbt.Project$.extract(Project.scala:320)
	at sbt.BuiltinCommands$.sbt$BuiltinCommands$$notifyUsersAboutShell(Main.scala:576)
	at sbt.BuiltinCommands$$anonfun$notifyUsersAboutShell$1.apply(Main.scala:584)
	at sbt.BuiltinCommands$$anonfun$notifyUsersAboutShell$1.apply(Main.scala:584)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.runCmd$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:187)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Session not initialized.
[error] Use 'last' for the full log.




if  click l then:


[debug] Parsing /Users/sanbo/dev/sdk/add-ons/addon-google_apis-google-24/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/17.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/18.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/18.1.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/18.1.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/19.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/19.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/19.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/19.0.3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/19.1.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/20.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.1.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.1.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/21.1.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/22.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/22.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/23.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/23.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/23.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/23.0.3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/24.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/24.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/24.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/24.0.3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/25.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/25.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/25.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/25.0.3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/26.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/26.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/26.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/27.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/build-tools/27.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/cmake/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/docs/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/emulator/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/android/gapid/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/android/gapid_3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/android/m2repository/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/android/support/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/admob_ads_sdk/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/analytics_sdk_v2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/auto/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/gcm/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/google_play_services/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/google_play_services_froyo/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/instantapps/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/m2repository/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/market_apk_expansion/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/market_licensing/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/play_apk_expansion/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/play_billing/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/play_licensing/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/simulators/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/google/webdriver/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha4/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha5/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha6/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha7/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha8/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-alpha9/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-beta1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-beta2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-beta3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-beta4/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.0-beta5/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha4/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha5/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha6/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha7/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha8/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-alpha9/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-beta1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-beta2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-beta3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-beta4/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.0-beta5/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/extras/saurikit/cydia_substrate/package.xml
[debug] Parsing legacy package: /Users/sanbo/dev/sdk/lldb
[debug] Parsing /Users/sanbo/dev/sdk/ndk-bundle/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/patcher/v1/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/patcher/v3/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/patcher/v4/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platform-tools/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-10/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-11/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-12/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-13/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-14/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-15/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-16/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-17/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-18/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-19/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-20/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-21/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-22/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-23/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-24/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-25/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-26/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-27/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-7/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-8/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/platforms/android-9/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/samples/android-23/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-14/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-15/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-16/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-17/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-18/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-19/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-20/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-21/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-22/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-23/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-24/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-25/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/sources/android-26/package.xml
[debug] Parsing /Users/sanbo/dev/sdk/tools/package.xml
[debug] Load.apply: Def.make(settings)... took 6389.914005 ms
[debug] Load.apply: structureIndex took 412.005346 ms
[debug] Load.apply: mkStreams took 0.002833 ms
[info] Set current project to shadowsocks-android (in build file:/Users/sanbo/code/ss/shadowsocks-android/)
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
[debug] > load-failed
[debug] > last
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by hhhaiai** [comment]
what can I do?

**Comment by Mygod** [comment]
Report to sbt-android instead.
