### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by chenleicrm** [shadowsocks/shadowsocks-android#1474]
### What did you do?
sbt clean go-build android:package-release
### What did you expect to see?
expect build success

### What did you see instead?
[warn] Android SDK updates available, run 'android-update' to update:
[warn]     Google Play Intel x86 Atom System Image
[warn]     Google APIs Intel x86 Atom_64 System Image
[warn]     Google APIs Intel x86 Atom_64 System Image
[warn]     Android SDK Platform-Tools
[warn]     Google APIs Intel x86 Atom System Image
[error] cmd/compile/internal/gc
[error] cmd/compile/internal/amd64
[error] cmd/compile/internal/arm
[error] cmd/compile/internal/arm64
[error] cmd/compile/internal/mips
[error] cmd/compile/internal/mips64
[error] cmd/compile/internal/ppc64
[error] cmd/compile/internal/s390x
[error] cmd/compile/internal/x86
[error] cmd/compile
[info] 
[info] 
[info] ---
[info] Installed Go for darwin/amd64 in /Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/src/overture/go
[info] Installed commands in /Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/src/overture/go/bin
[info] ~/Desktop/socks1202/shadowsocks-android
[info] Get dependences for overture
[error] mobile/src/overture/make.bash: line 62: pushd: /Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/src/overture/src/github.com/shadowsocks/overture/main: No such file or directory
[error] godep: [WARNING]: godep should only be used inside a valid go package directory and
[error] godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
[error] godep: [WARNING]:	Current Directory: /Users/chenlei/Desktop/socks1202/shadowsocks-android
[error] godep: [WARNING]:	$GOPATH: /Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/src/overture
[error] godep: open Godeps/Godeps.json: no such file or directory
[info] Cross compile overture for arm
[error] can't load package: package .: no Go files in /Users/chenlei/Desktop/socks1202/shadowsocks-android
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $3064c566fd1002c0bb70$$anonfun$$sbtdef$1.apply(/Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/build.sbt:69)
	at $3064c566fd1002c0bb70$$anonfun$$sbtdef$1.apply(/Users/chenlei/Desktop/socks1202/shadowsocks-android/mobile/build.sbt:66)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (mobile/*:goBuild) Native build script exit code: 255
[error] Total time: 97 s, completed 2017-12-2 13:54:49

**Comment by Mygod** [comment]
Read log and instructions and put down your finger.
