### ISSUE TITLE
分享到二维码/NFC导致程序停止运行

### ISSUE THREAD

**Issue by iamsad3508** [shadowsocks/shadowsocks-android#1500]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: android 8.1.0 ""OPM1.171019.011"
* Device: nexus 6p
* Shadowsocks version: 4.4.0
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ x] IPv4 server address
* [ ] IPv6 server address
* [x ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:aes-256-cfb
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x ] Apps VPN mode
  * [ x] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
按分享键到"二维码/NFC"

### What did you expect to see?
成功

### What did you see instead?
"影梭已停止运行"，vpn依然连接状态

**Comment by Mygod** [comment]
@madeye I can't seem reproduce this issue locally.

**Comment by madeye** [comment]
I think It's a Android 8.1 specific issue. I can reproduce it on Android 8.1, Pixel.

**Comment by Mygod** [comment]
It works on 8.1 emulator though.

**Comment by madeye** [comment]
2fa8c7 causing the issue again.

```
12-15 12:00:17.026 28356 28356 E AndroidRuntime: java.lang.IllegalStateException: Fragment com.github.shadowsocks.ProfilesFragment.QRCodeDialog must be a public static class to be  properly recreated from instance state.
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:396)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:375)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at com.github.shadowsocks.ProfilesFragment$ProfileViewHolder.onMenuItemClick(ProfilesFragment.kt:212)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:108)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.AbsListView.onTouchUp(AbsListView.java:4054)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3813)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:11776)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2406)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:12015)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:325)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:142)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-15 12:00:17.026 28356 28356 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-15 12:00:17.032   887  1338 W ActivityManager:   Force finishing activity com.github.shadowsocks/.MainActivity
```

**Comment by Mygod** [comment]
OK I see.
