### ISSUE TITLE
crash__________beginning

### ISSUE THREAD

**Issue by 1chick** [shadowsocks/shadowsocks-android#1748]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you expect to see?
04-11 15:42:45.066 1664-1664/com.github.shadowsocks E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.github.shadowsocks, PID: 1664
                                                                      java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.google.android.iot.frameworkpackagestubs/.Stubs$VpnConfirmDialogStub } from ProcessRecord{ae5ed4 1664:com.github.shadowsocks/u0a29} (pid=1664, uid=10029) not exported from uid 10023
                                                                          at android.os.Parcel.readException(Parcel.java:2004)
                                                                          at android.os.Parcel.readException(Parcel.java:1950)
                                                                          at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4352)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:4488)
                                                                          at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:4446)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
                                                                          at com.github.shadowsocks.MainActivity$onCreate$2.onClick(MainActivity.kt:279)
                                                                          at android.view.View.performClick(View.java:6294)
                                                                          at android.view.View$PerformClick.run(View.java:24770)
                                                                          at android.os.Handler.handleCallback(Handler.java:790)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by taweesakteejantuk66** [comment]
good
