### ISSUE TITLE
Can't connect when "Apps VPN Mode" enabled

### ISSUE THREAD

**Issue by fconn** [shadowsocks/shadowsocks-android#1757]
### Environment

* Android version: Resurrection Remix 5.8.5 (Android 7.1.2)
* Device: Wileyfox Swift 2 Plus
* Shadowsocks version: 4.5.6
* Last version that did not exhibit the issue (if applicable): no

### Configuration

* [x] IPv4 server address
* [x] IPv6 server address
* [x] Client IPv4 availability
* [x] Client IPv6 availability
* Encrypt method: CHACHA20-IETF-POLY1305
* Route
  * [ ] All
  * [x] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [x] IPv6 route
* [x] Apps VPN mode
  * [x] Bypass mode
* Remote DNS: 9.9.9.10
* [x] DNS Forwarding
* Plugin configuration (if applicable): Simple obfuscation
* [x] Auto Connect
* [x] TCP Fast Open
* If you're not using VPN mode, please supply more details here: no

### What did you do?
I trying to connect with "Apps VPN Mode" enabled.

### What did you expect to see?
Normal work.

### What did you see instead?
![screenshot_20180416-131126](https://user-images.githubusercontent.com/37580200/38804163-19fcc77c-417a-11e8-9990-964f75009f1a.png)

**When "Apps VPN Mode" disabled all works perfectly.**

**Comment by fconn** [comment]
There is excert from logcat

```
04-16 13:36:01.189  3139 10974 I ActivityManager: Start proc 6202:com.github.shadowsocks.plugin.obfs_local/u0a100 for content provider com.github.shadowsocks.plugin.obfs_local/.BinaryProvider
04-16 13:36:01.254  6202  6202 I art     : Starting a blocking GC AddRemoveAppImageSpace
04-16 13:36:01.255  3139  3311 E AlarmManager: RTC Alarm: 2 null com.google.android.gms com.google.android.gms.analytics.ANALYTICS_DISPATCH
04-16 13:36:01.294  6221  6221 W linker  : /data/app/com.github.shadowsocks-2/lib/arm64/libss-local.so: unsupported flags DT_FLAGS_1=0x8000001
04-16 13:36:01.298  3455  6223 I GuardedProcessPool: WARNING: linker: /data/app/com.github.shadowsocks-2/lib/arm64/libss-local.so: unsupported flags DT_FLAGS_1=0x8000001
04-16 13:36:01.321  6221  6221 D shadowsocks: initializing acl...
04-16 13:36:01.322  6221  6221 D shadowsocks: plugin "/data/app/com.github.shadowsocks.plugin.obfs_local-1/lib/arm/libobfs-local.so --fast-open -V" enabled
04-16 13:36:01.322  6221  6221 D shadowsocks: using tcp fast open
04-16 13:36:01.323  6221  6221 D shadowsocks: initializing ciphers... chacha20-ietf-poly1305
04-16 13:36:01.323  6221  6221 D shadowsocks: listening at 127.0.0.1:1080
04-16 13:36:01.323  6221  6221 D shadowsocks: udprelay enabled
04-16 13:36:01.364  6225  6225 D simple-obfs: using tcp fast open
04-16 13:36:01.364  6225  6225 D simple-obfs: obfuscating enabled
04-16 13:36:01.364  6225  6225 D simple-obfs: obfuscating hostname: vk.com
04-16 13:36:01.364  6225  6225 D simple-obfs: tcp port reuse enabled
04-16 13:36:01.364  6225  6225 D simple-obfs: listening at 127.0.0.1:57790
04-16 13:36:01.372  3139 10655 D Vpn     : setting state=CONNECTING, reason=establish
04-16 13:36:01.385  3139 10655 D VpnJni  : Address added on tun0: 26.26.26.1/24
04-16 13:36:01.386  3139 10655 D VpnJni  : Address added on tun0: fdfe:dcba:9876::1/126
04-16 13:36:01.405  3139 10655 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTING/CONNECTING, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false, metered: false]}  network{229}  nethandle{983563946718}  lp{{InterfaceName: tun0 LinkAddresses: [26.26.26.1/24,fdfe:dcba:9876::1/126,]  Routes: [::/0 -> :: tun0,1.0.0.0/8 -> 0.0.0.0 tun0,2.0.0.0/7 -> 0.0.0.0 tun0,4.0.0.0/6 -> 0.0.0.0 tun0,8.0.0.0/7 -> 0.0.0.0 tun0,11.0.0.0/8 -> 0.0.0.0 tun0,12.0.0.0/6 -> 0.0.0.0 tun0,16.0.0.0/4 -> 0.0.0.0 tun0,32.0.0.0/3 -> 0.0.0.0 tun0,64.0.0.0/3 -> 0.0.0.0 tun0,96.0.0.0/6 -> 0.0.0.0 tun0,100.0.0.0/10 -> 0.0.0.0 tun0,100.128.0.0/9 -> 0.0.0.0 tun0,101.0.0.0/8 -> 0.0.0.0 tun0,102.0.0.0/7 -> 0.0.0.0 tun0,104.0.0.0/5 -> 0.0.0.0 tun0,112.0.0.0/10 -> 0.0.0.0 tun0,112.64.0.0/11 -> 0.0.0.0 tun0,112.96.0.0/12 -> 0.0.0.0 tun0,112.112.0.0/13 -> 0.0.0.0 tun0,112.120.0.0/14 -> 0.0.0.0 tun0,112.124.0.0/19 -> 0.0.0.0 tun0,112.124.32.0/21 -> 0.0.0.0 tun0,112.124.40.0/22 -> 0.0.0.0 tun0,112.124.44.0/23 -> 0.0.0.0 tun0,112.124.46.0/24 -> 0.0.0.0 tun0,112.124.48.0/20 -> 0.0.0.0 tun0,112.124.64.0/18 -> 0.0.0.0 tun0,112.124.128.0/17 -> 0.0.0.0 tun0,112.125.0.0/16 -> 0.0.0.0 tun0,112.126.0.0/15 -> 0.0.0.0 tun0,112.128.0.0/9 -> 0.0.0.0 tun0,113.0.0.0/8 -> 0.0.0.0 tun0,114.0.0.0/10 -> 0.0.0.0 tun0,114.64.0.0/11 -> 0.0.0.0 tun0,114.96.0.0/12 -> 0.0.0.0 tun0,114.112.0.0/15 -> 0.0.0.0 tun0,114.114.0.0/18 -> 0.0.0.0 tun0,114.114.64.0/19 -> 0.0.0.0 tun0,114.114.96.0/20 -> 0.0.0.0 tun0,114.114.112.0/23 -> 0.0.0.0 tun0,114.114.115.0/24 -> 0.0.0.0 tun0,114.114.116.0/22 -> 0.0.0.0 tun0,114.114.120.0/21 -> 0.0.0.0 tun0,114.114.128.0/17 -> 0.0.0.0 tun0,114.115.0.0/16 -> 0.0.0.0 tun0,114.116.0.0/14 -> 0.0.0.0 tun0,114.120.0.0/13 -> 0.0.0.0 tun0,114.128.0.0/9 -> 0.0.0.0 tun0,115.0.0.0/8 -> 0.0.0.0 tun0,116.0.0.0/6 -> 0.0.0.0 tun0,120.0.0.0/6 -> 0.0.0.0 tun0,124.0.0.0/7 -> 0.0.0.0 tun0,126.0.0.0/8 -> 0.0.0.0 tun0,128.0.0.0/3 -> 0.0.0.0 tun0,160.0.0.0/5 -> 0.0.0.0 tun0,168.0.0.0/8 -> 0.0.0.0 tun0,169.0.0.0/9 -> 0.0.0.0 tun0,169.128.0.0/10 -> 0.0.0.0 tun0,169.192.0.0/11 -> 0.0.0.0 tun0,169.224.0.0/12 -> 0.0.0.0 tun0,169.240.0.0/13 -> 0.0.0.0 tun0,169.248.0.0/14 -> 0.0.0.0 tun0,169.252.0.0/15 -> 0.0.0.0 tun0,169.255.0.0/16 -> 0.0.0.0 tun0,170.0.0.0/7 -> 0.0.0.0 tun0,172.0.0.0/12 -> 0.0.0.0 tun0,172.32.0.0/11 -> 0.0.0.0 tun0,172.64.0.0/10 -> 0.0.0.0 tun0,172.128.0.0/9 -> 0.0.0.0 tun0,173.0.0.0/8 -> 0.0.0.0 tun0,174.0.0.0/7 -> 0.0.0.0 tun0,176.0.0.0/4 -> 0.0.0.0 tun0,192.0.0.8/29 -> 0.0.0.0 tun0,192.0.0.16/28 -> 0.0.0.0 tun0,192.0.0.32/27 -> 0.0.0.0 tun0,192.0.0.64/26 -> 0.0.0.0 tun0,192.0.0.128/25 -> 0.0.0.0 tun0,192.0.1.0/24 -> 0.0.0.0 tun0,192.0.3.0/24 -> 0.0.0.0 tun0,192.0.4.0/22 -> 0.0.0.0 tun0,192.0.8.0/21 -> 0.0.0.0 tun0,192.0.16.0/20 -> 0.0.0.0 tun0,192.0.32.0/19 -> 0.0.0.0 tun0,192.0.64.0/18 -> 0.0.0.0 tun0,192.0.128.0/17 -> 0.0.0.0 tun0,192.1.0.0/16 -> 0.0.0.0 tun0,192.2.0.0/15 -> 0.0.0.0 tun0,192.4.0.0/14 -> 0.0.0.0 tun0,192.8.0.0/13 -> 0.0.0.0 tun0,192.16.0.0/12 -> 0.0.0.0 tun0,192.32.0.0/11 -> 0.0.0.0 tun0,192.64.0.0/12 -> 0.0.0.0 tun0,192.80.0.0/13 -> 0.0.0.0 tun0,192.88.0.0/18 -> 0.0.0.0 tun0,192.88.64.0/19 -> 0.0.0.0 tun0,192.88.96.0/23 -> 0.0.0.0 tun0,192.88.98.0/24 -> 0.0.0.0 tun0,192.88.100.0/22 -> 0.0.0.0 tun0,192.88.104.0/21 -> 0.0.0.0 tun0,192.88.112.0/20 -> 0.0.0.0 tun0,192.88.128.0/17 -> 0.0.0.0 tun0,192.89.0.0/16 -> 0.0.0.0 tun0,192.90.0.0/15 -> 0.0.0.0 tun0,192.92.0.0/14 -> 0.0.0.0 tun0,192.96.0.0/11 -> 0.0.0.0 tun0,192.128.0.0/11 -> 0.0.0.0 tun0,192.160.0.0/13 -> 0.0.0.0 tun0,192.169.0.0/16 -> 0.0.0.0 tun0,192.170.0.0/15 -> 0.0.0.0 tun0,192.172.0.0/14 -> 0.0.0.0 tun0,192.176.0.0/12 -> 0.0.0.0 tun0,192.192.0.0/10 -> 0.0.0.0 tun0,193.0.0.0/8 -> 0.0.0.0 tun0,194.0.0.0/7 -> 0.0.0.0 tun0,196.0.0.0/7 -> 0.0.0.0 tun0,198.0.0.0/12 -> 0.0.0.0 tun0,198.16.0.0/15 -> 0.0.0.0 tun0,198.20.0.0/14 -> 0.0.0.0 tun0,198.24.0.0/13 -> 0.0.0.0 tun0,198.32.0.0/12 -> 0.0.0.0 tun0,198.48.0.0/15 -> 0.0.0.0 tun0,198.50.0.0/16 -> 0.0.0.0 tun0,198.51.0.0/18 -> 0.0.0.0 tun0,198.51.64.0/19 -> 0.0.0.0 tun0,198.51
04-16 13:36:01.405  3139  3566 D ConnectivityService: NetworkAgentInfo [VPN () - 229] EVENT_NETWORK_INFO_CHANGED, going from null to CONNECTING
04-16 13:36:01.419  2735  3461 D NetlinkEvent: Unknown ifindex 86 in RTM_DELADDR
04-16 13:36:01.554  3455  6201 W System.err: java.lang.SecurityException: get package uid: Neither user 10134 nor current process has android.permission.INTERACT_ACROSS_USERS.
04-16 13:36:01.554  3455  6201 W System.err: 	at android.os.Parcel.readException(Parcel.java:1684)
04-16 13:36:01.554  3455  6201 W System.err: 	at android.os.Parcel.readException(Parcel.java:1637)
04-16 13:36:01.554  3455  6201 W System.err: 	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1966)
04-16 13:36:01.554  3455  6201 W System.err: 	at android.net.VpnService$Builder.establish(VpnService.java:769)
04-16 13:36:01.554  3455  6201 W System.err: 	at com.github.shadowsocks.bg.VpnService.startVpn(VpnService.kt:229)
04-16 13:36:01.554  3455  6201 W System.err: 	at com.github.shadowsocks.bg.VpnService.startNativeProcesses(VpnService.kt:178)
04-16 13:36:01.554  3455  6201 W System.err: 	at com.github.shadowsocks.bg.BaseService$Interface$onStartCommand$1.invoke(BaseService.kt:407)
04-16 13:36:01.554  3455  6201 W System.err: 	at com.github.shadowsocks.bg.BaseService$Interface$onStartCommand$1.invoke(BaseService.kt:229)
04-16 13:36:01.554  3455  6201 W System.err: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
04-16 13:36:01.567  3421  3421 E ShadowsocksMainActivity: Error to start VPN service: Failed to connect the remote server: get package uid: Neither user 10134 nor current process has android.permission.INTERACT_ACROSS_USERS.

```

**Comment by Mygod** [comment]
Duplicate with #1184 #1463.
