### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by Alisin** [shadowsocks/shadowsocks-android#1764]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: EMUI4.0.1 (android 6.0)
* Device: HUAWEI honor 6
* Shadowsocks version: v4.5.6
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

### What did you do?
build and run

### What did you see instead?
app crash on start

**Comment by Alisin** [comment]
$ adb shell am start -n "com.github.shadowsocks/com.github.shadowsocks.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 24426 on device huawei-h60_l01-7N2SSE154T027697
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/HAL: load: id=gralloc != hmi->id=gralloc
W/ComponentDiscovery: Application info not found.
                      Could not retrieve metadata, returning empty list of registrars.
I/FirebaseInitProvider: FirebaseApp initialization successful
I/HwCust: Constructor found for class android.app.HwCustAlarmManagerImpl
I/FA: App measurement is starting up, version: 12451
      To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
      To enable faster debug mode event logging run:
        adb shell setprop debug.firebase.analytics.app com.github.shadowsocks
W/GooglePlayServicesUtil: Google Play Store is missing.
W/GooglePlayServicesUtil: Google Play Store is missing.
I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$JobServiceEngineImpl>
       Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$JobServiceEngineImpl>
W/GooglePlayServicesUtil: Google Play Store is missing.
W/FA: Service invalid
W/FirebaseInstanceId: Failed to resolve IID implementation package, falling back
I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/GooglePlayServicesUtil: Google Play Store is missing.
W/GooglePlayServicesUtil: Google Play Store is missing.
I/FA: Tag Manager is not found and thus will not be used
I/Process: Sending signal. PID: 24426 SIG: 9
Application terminated.

**Comment by Alisin** [comment]
I download an apk armeabi-7a-v4.5.6 below and it works fine.
[https://github.com/shadowsocks/shadowsocks-android/releases](url)

**Comment by Alisin** [comment]
04-19 18:14:10.470 19717-19717/com.github.shadowsocks E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.shadowsocks, PID: 19717
    java.lang.RuntimeException: Unable to instantiate service com.google.android.gms.measurement.AppMeasurementService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/com.github.shadowsocks-2/base.apk"],nativeLibraryDirectories=[/data/app/com.github.shadowsocks-2/lib/arm, /data/app/com.github.shadowsocks-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2890)
        at android.app.ActivityThread.access$1900(ActivityThread.java:165)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/com.github.shadowsocks-2/base.apk"],nativeLibraryDirectories=[/data/app/com.github.shadowsocks-2/lib/arm, /data/app/com.github.shadowsocks-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
        at android.app.ActivityThread.access$1900(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5546) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
      Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurementService
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by V-E-O** [comment]
https://github.com/shadowsocks/shadowsocks-android/commit/635105ca059cf5835564881a0be1082ad8e5fc02

**Comment by Alisin** [comment]
@V-E-O thanks, changing playServicesVersion back to  '12.0.1' fixed the crash.

**Comment by Mygod** [comment]
@madeye Could you create a release build and see if you can reproduce this?
