### ISSUE TITLE
Build command failed

### ISSUE THREAD

**Issue by xxliang** [shadowsocks/shadowsocks-android#1787]
Can you tell me why I build command failed.  I find the problem from issues but I can't find the answer or Can you tell me which issue? I am new on android and I am not good at ndk .

Build command failed.
Error while executing process /Users/xiong/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/*
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/gdbserver
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/lib/x86/gdb.setup
mkdir -p /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper
echo [x86] "Compile++      ": "jni-helper <= jni-helper.cpp"
/Users/xiong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o.d -gcc-toolchain /Users/xiong/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -I/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/libancillary -I/Users/xiong/Library/Android/sdk/ndk-bundle/sources/android/cpufeatures -I/Users/xiong/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -I/Users/xiong/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -I/Users/xiong/Library/Android/sdk/ndk-bundle/sources/android/support/include -I/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni -std=c++11    -DANDROID -std=c++11 -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign   --sysroot /Users/xiong/Library/Android/sdk/ndk-bundle/sysroot -isystem /Users/xiong/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/jni-helper.cpp -o /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/jni-helper/jni-helper.o
mkdir -p /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuildmake: *** No rule to make target `/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/libancillary/fd_recv.c', needed by `/Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/ancillary/libancillary/fd_recv.o'.  Stop.
/release/obj/local/x86
mkdir -p /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures
echo [x86] "Compile        ": "cpufeatures <= cpu-features.c"
/Users/xiong/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -MMD -MP -MF /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o.d -gcc-toolchain /Users/xiong/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 -target i686-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -O2 -DNDEBUG  -I/Users/xiong/Library/Android/sdk/ndk-bundle/sources/android/cpufeatures   -DANDROID -Wall -Wextra -Werror -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -mstackrealign  --sysroot /Users/xiong/Library/Android/sdk/ndk-bundle/sysroot -isystem /Users/xiong/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -c  /Users/xiong/Library/Android/sdk/ndk-bundle/sources/android/cpufeatures/cpu-features.c -o /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
echo [x86] "StaticLibrary  ": "libcpufeatures.a"
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a
/Users/xiong/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-ar crsD  /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/libcpufeatures.a /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/release/obj/local/x86/objs/cpufeatures/cpu-features.o
Build command failed.
Error while executing process /Users/xiong/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/xiong/Documents/proxifier/shadowsocks-android/core/src/main/jni/Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/*
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdbserver
rm -f /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86/gdb.setup
mkdir -p /Users/xiong/Documents/proxifier/shadowsocks-android/core/build/intermediates/ndkBuild/debug/lib/x86

**Comment by madeye** [comment]
Make sure you have pulled all the submodules.

**Comment by jackrow** [comment]
git submodule update --init --recursive ？

**Comment by xxliang** [comment]
Yes , I also try to do it. but some submodules download fail. Did you compile successfully？

**Comment by xxliang** [comment]
I download submodule one by one and put them into the specified directory. It doesn't work.

**Comment by jackrow** [comment]
I succeeded in compiling and installed, but ss can't connect. What about you?

**Comment by nchennan** [comment]
@jackrow ，I still failed to compile，How to operate, Thank you ！

**Comment by jackrow** [comment]
What problems do you have? See if it's the same as me.

**Comment by nchennan** [comment]
@jackrow ，估计是没有科学上网，你可以把编译成功的源码发给我吗？邮箱地址:chen_nan_ping@sina.cn, 谢谢！

**Comment by jackrow** [comment]
不是很理解，没有科学上网？

**Comment by rockykou** [comment]
@jackrow I met the same problem，and I tried to fix with cloning the submodules,but failed.Can you send the successed building source code to this email , kouzhen168@gmail.com,  thank you very much, I am waiting for you.

**Comment by Wingge** [comment]
I met the same problem，and I tried to fix with cloning the submodules,but failed.Can you send the successed building source code to this email , zhongzhai@163.com, thank you very much, I am waiting for you.

**Comment by Wingge** [comment]
My problem is :
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:goBuild'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:37)
	at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 33 more

**Comment by Wingge** [comment]
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:goBuild'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cmd.exe'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:37)
	at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 33 more

`

**Comment by 174high** [comment]
@jackrow 我这边也编译失败，麻烦也发一份编译成功的源码到我邮箱 [466243346@qq.com]， 先谢了
