### ISSUE TITLE
Crash When App Start

### ISSUE THREAD

**Issue by crystal-lee** [shadowsocks/shadowsocks-android#1866]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: "5.1"*
* Device: *ZTE BV0720*
* Shadowsocks version: *version code "v4.6.1" or commit ID "8aabc73b9698b2bb26a89717d59ac1660e79fad8"*

### What did you do?
when the app is start，the crash happened!
```
AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.github.shadowsocks, PID: 16708
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeE
                            xception: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
                         E      at android.app.ActivityThread.access$800(ActivityThread.java:178)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                         E      at android.os.Handler.dispatchMessage(Handler.java:111)
                         E      at android.os.Looper.loop(Looper.java:194)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5644)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1059)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
                         E  Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
                         E      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
                         E      at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
                         E      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
                         E      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                         E      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
                         E      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                         E      at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218)
                         E      at android.app.Activity.performCreate(Activity.java:6113)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
                         E      ... 10 more
                         E  Caused by: java.lang.reflect.InvocationTargetException
                         E      at java.lang.reflect.Constructor.newInstance(Native Method)
                         E      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                         E      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
                         E      ... 23 more
                         E  Caused by: kotlin.KotlinNullPointerException
                         E      at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
                         E      ... 26 more
```

### What did you expect to see?
how to solve it ?

**Comment by crystal-lee** [comment]
can not resolve it problem。。。。。。

**Comment by Mygod** [comment]
Did you compile the latest commit?
