### ISSUE TITLE
I got an crash, when start shadowsocks!!!!

### ISSUE THREAD

**Issue by kigkrazy** [shadowsocks/shadowsocks-android#1868]
Please read FAQ then answer these questions before submitting your issue. Thanks!

### Environment

Android version: "5.1"*
Device: NEXUS5
android os: ***cyanogenmod 12.1***
Shadowsocks version: version code "v4.6.1" or commit ID "c6676b50df0225cd5f94add09e203a558e98937f"

### What did you do?
build it by myself, but the apk don't work. I got some crash below!!!!
do something throw [Crash When App Start](https://github.com/shadowsocks/shadowsocks-android/issues/1866), but it no use.  
I install the release apk, “shadowsocks--universal-4.6.1.apk”， it also error。
### What did you see instead?
```
07-12 10:33:48.320 6433-6433/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.shadowsocks, PID: 6433
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5294)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
     Caused by: kotlin.KotlinNullPointerException
        at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620) 
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:808) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5294) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 

```

**Comment by madeye** [comment]
Disable Xposed and try again.

**Comment by kigkrazy** [comment]
I found and try, the same error!!! 
I build `v4.5.7`, it run success, I think there is some thing wrong in the code.

**Comment by crystal-lee** [comment]
I pull the latest commit ,but also this error!
```
commit deb297a838ca4452fb17e648996b653fe5a7270c (HEAD -> master, origin/master, origin/HEAD)
Author: Mygod <contact-github@mygod.be>
Date:   Thu Jul 12 17:17:46 2018 +0800

    Add #1821 to FAQ
```

```
 AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.github.shadowsocks, PID: 3877
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeE
                            xception: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                         E      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                         E  Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
                         E      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
                         E      at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
                         E      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
                         E      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                         E      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
                         E      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                         E      at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:220)
                         E      at android.app.Activity.performCreate(Activity.java:5990)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                         E      ... 10 more
                         E  Caused by: java.lang.reflect.InvocationTargetException
                         E      at java.lang.reflect.Constructor.newInstance(Native Method)
                         E      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                         E      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
                         E      ... 23 more
                         E  Caused by: kotlin.KotlinNullPointerException
                         E      at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
                         E      ... 26 more
```

**Comment by Mygod** [comment]
Can you replace `ShrinkUpwardBehavior.kt:L38`:
```kotlin
private val accessibility = context.systemService<AccessibilityManager>()
```
with
```kotlin
private val accessibility = context.getSystemService(Context.ACCESSIBILITY_SERVICE) as AccessibilityManager
```
and try again?

**Comment by crystal-lee** [comment]
it is ok
the crash is not happened

**Comment by Mygod** [comment]
Does the official 4.6.x apk crash on your device? If not, you should open an issue at [Google's issue tracker](https://issuetracker.google.com) about `ContextCompat.getSystemService` for `AccessibilityManager` doesn't work properly on your device.

**Comment by crystal-lee** [comment]
the official 4.6.x apk does not crash on my device!
but I am a beginner of android ,don't know how to open an issue at Google's issue tracker

**Comment by kigkrazy** [comment]
I can solved problem by this?
```
private val accessibility = context.systemService<AccessibilityManager>()
with
private val accessibility = context.getSystemService(Context.ACCESSIBILITY_SERVICE) as AccessibilityManager
```

**Comment by crystal-lee** [comment]
yes, it work ok on my device,
 I can only edit config to use ,can not scan code to import ,because my device has not gms

**Comment by Mygod** [comment]
Then I suppose it's something to do with your build process instead.

**Comment by Mygod** [comment]
Try https://github.com/shadowsocks/shadowsocks-android/commit/f053a62f779c8063d56e7de54fa1c9accec5a33d. (ignore travis build failing, it's lint bug)

**Comment by caobug** [comment]
@Mygod  @madeye After modification, no crashes.

`private val accessibility = context.getSystemService(Context.ACCESSIBILITY_SERVICE) as AccessibilityManager
`

**Comment by Mygod** [comment]
Please try #1903. Debug apk: https://16-31254465-gh.circle-artifacts.com/0/apk/debug/mobile-universal-debug.apk
