### ISSUE TITLE
4.6.1 版本奔溃

### ISSUE THREAD

**Issue by oahgnez** [shadowsocks/shadowsocks-android#1976]
环境：最新官方4.6.1版本，Android5.1 （魅族）
ps：打开必定闪退，4.6.1模拟器打开正常，4.6.0版本真机正常。
无法inflate ShrinkUpwardBehavior？报错如下：

10-12 20:55:17.046 16711-16736/? W/FA: Service invalid
10-12 20:55:17.055 16711-16740/? E/FirebaseInstanceId: Google Play services missing or without correct permission.
10-12 20:55:17.095 16679-16679/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.shadowsocks, PID: 16679
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.access$900(ActivityThread.java:187)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5877)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:814)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218)
        at android.app.Activity.performCreate(Activity.java:6127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747) 
        at android.app.ActivityThread.access$900(ActivityThread.java:187) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5877) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:814) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:6127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747) 
        at android.app.ActivityThread.access$900(ActivityThread.java:187) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5877) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
     Caused by: kotlin.KotlinNullPointerException
        at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620) 
        at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704) 
        at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:814) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218) 
        at android.app.Activity.performCreate(Activity.java:6127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747) 
        at android.app.ActivityThread.access$900(ActivityThread.java:187) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5877) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by Mygod** [comment]
This would be fixed by the next release.
