### ISSUE TITLE
(slove)problem to run mobile

### ISSUE THREAD

**Issue by mohtasham1988** [shadowsocks/shadowsocks-android#1978]
I have a problem when running the app with an error 'Cause: java.lang.NullPointerException'
but gradle sync is ok.
I Have ubuntu and did config step by step
 how can I fix this problem?

 

> java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.NullPointerException
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.GeneratedMethodAccessor816.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at

**Comment by mohtasham1988** [comment]
I fixed this
unChecked Enable Instance
![screenshot from 2018-10-21 07-45-17](https://user-images.githubusercontent.com/22011648/47266569-5debe300-d545-11e8-9db7-c64db3cfb8eb.png)
