### ISSUE TITLE
crash on android 5.0.2, redmi note2

### ISSUE THREAD

**Issue by JackyMR** [shadowsocks/shadowsocks-android#2014]
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.MainActivity}: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2489)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2551)
	at android.app.ActivityThread.access$1000(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5581)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.github.shadowsocks.widget.ShrinkUpwardBehavior
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:622)
	at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2805)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1704)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:111)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.github.shadowsocks.MainActivity.onCreate(MainActivity.kt:218)
	at android.app.Activity.performCreate(Activity.java:6034)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2442)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:620)
	... 23 more
Caused by: kotlin.KotlinNullPointerException
	at com.github.shadowsocks.widget.ShrinkUpwardBehavior.<init>(ShrinkUpwardBehavior.kt:69)
	... 26 more

**Comment by JackyMR** [comment]
the newest version，4.6.1

**Comment by Mygod** [comment]
This should be fixed in 4.6.2.
