### ISSUE TITLE
v4.8.0 crash on Apps VPN mode

### ISSUE THREAD

**Issue by m5h1** [shadowsocks/shadowsocks-android#2234]
**Describe the bug**
The application crashes when trying to save Apps VPN Mode settings 

**To Reproduce**
1. Open the application 
2. Add Profile --> Manual Settings --> Apps VPN Mode 
3. Turn on Apps VPN Mode for a few Apps 
4. Try to save the profile 
5. The app will either 
	A. Stop responding 
	B. The screen becomes fully white for a fraction of a second and go back to main menu
6. In both cases the Apps VPN Mode setting is not saved  

**Expected behavior**
Apps VPN Mode setting should be saved normally without error 

**Screenshots**
![Screenshot_20190608-222429](https://user-images.githubusercontent.com/5536733/59151193-db665400-8a3f-11e9-82b5-ac63b5aeebf7.jpg)

**Smartphone**
 - Android/Chrome OS version: Android 9 Build PQ3A.190605.003 June 5, 2019 Patch 
 - Device: Google Pixel 3
 - Version: v4.8.0
 - Last version that did not exhibit the issue: 

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [X] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I attached the phone to logcat, and got the following 

`06-08 21:22:12.905 20731 20731 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c15f198
06-08 21:22:14.914 20731 20731 D AndroidRuntime: Shutting down VM
06-08 21:22:14.915 20731 20731 E AndroidRuntime: FATAL EXCEPTION: main
06-08 21:22:14.915 20731 20731 E AndroidRuntime: Process: com.github.shadowsocks, PID: 20731
06-08 21:22:14.915 20731 20731 E AndroidRuntime: java.lang.IllegalStateException: Check failed.
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.github.shadowsocks.database.Profile.deserialize(Profile.kt:311)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.github.shadowsocks.ProfileConfigFragment.saveAndExit(ProfileConfigFragment.kt:138)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.github.shadowsocks.ProfileConfigFragment.onOptionsItemSelected(ProfileConfigFragment.kt:211)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.github.shadowsocks.ProfileConfigActivity.onOptionsItemSelected(ProfileConfigActivity.kt:73)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:3544)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25885)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-08 21:22:14.915 20731 20731 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by huanght1997** [comment]
Same problem here.
For me, everything is ok if I tap the back button at the bottom, but if I tap the back button on the ActionBar, the application crashes with the same exception you pasted.

**Comment by m-sharaf11** [comment]
@huanght1997 you are totally right. I just used the OS back button at the bottom and it saved with no problem. Thanks for the hint
