### ISSUE TITLE
点击打勾按钮停止运行

### ISSUE THREAD

**Issue by xushet** [shadowsocks/shadowsocks-android#2247]
time: 1561208255667
msg: java.lang.IllegalStateException: Check failed.
stacktrace: java.lang.IllegalStateException: Check failed.
	at com.github.shadowsocks.database.Profile.deserialize(Profile.kt:311)
	at com.github.shadowsocks.ProfileConfigFragment.saveAndExit(ProfileConfigFragment.kt:138)
	at com.github.shadowsocks.ProfileConfigFragment.onOptionsItemSelected(ProfileConfigFragment.kt:211)
	at com.github.shadowsocks.ProfileConfigActivity.onOptionsItemSelected(ProfileConfigActivity.kt:73)
	at android.app.Activity.onMenuItemSelected(Activity.java:3545)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:6617)
	at android.view.View.performClickInternal(View.java:6594)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25910)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6739)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

**Comment by Mygod** [comment]
#2234

**Comment by Mygod** [comment]
@madeye Should probably do a new release.
