### ISSUE TITLE
App crashes on specific device caused by okhttp when test network

### ISSUE THREAD

**Issue by DitFranXX** [shadowsocks/shadowsocks-android#2297]
Please read contributing guidelines. Thanks.

**Describe the bug**
Null point exception when test network in proxy mode.

**To Reproduce**
1. Set to proxy mode.
2. Touch any server
3. Connect to server
4. Touch status bar which can test network
5. App crashes

**Expected behavior**
Show ping toast

**Screenshots**
![SmartSelect_20190901-125232_Google Play services](https://user-images.githubusercontent.com/45893338/64071549-6cec0780-ccb7-11e9-8db3-1f599f1ce3bb.jpg)

**Smartphone (please complete the following information):** 
 - Android/Chrome OS version: Android Pie (9)
 - Device: Samsung Galaxy Note10 5G Exynos
 - Version: 4.8.4
 - Last version that did not exhibit the issue: don't know

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: chacha20-ieft-poly1305
* Route
  * [x] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [?] TCP Fast Open (It turned on without any setting)
* If you're not using VPN mode, please supply more details here: Proxy mode, Connected with adguard proxy mode. (SS app filtering is disabled). The proxy is working if doesn't trigger this bug.

**Additional context**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference
	at com.android.okhttp.internal.Util.closeQuietly(Util.java:96)
	at com.android.okhttp.internal.http.StreamAllocation.deallocate(StreamAllocation.java:293)
	at com.android.okhttp.internal.http.StreamAllocation.noNewStreams(StreamAllocation.java:257)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:967)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:498)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:434)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:565)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at com.github.shadowsocks.net.HttpsTest$testConnection$1$1.invokeSuspend(HttpsTest.kt:101)
	at com.github.shadowsocks.net.HttpsTest$testConnection$1$1.invoke(Unknown Source:10)
	at com.github.shadowsocks.utils.UtilsKt$useCancellable$$inlined$suspendCancellableCoroutine$lambda$2.invokeSuspend(Utils.kt:89)
	at (Coroutine boundary.()
	at com.github.shadowsocks.net.HttpsTest$testConnection$1.invokeSuspend(HttpsTest.kt:98)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference
	at com.android.okhttp.internal.Util.closeQuietly(Util.java:96)
	at com.android.okhttp.internal.http.StreamAllocation.deallocate(StreamAllocation.java:293)
	at com.android.okhttp.internal.http.StreamAllocation.noNewStreams(StreamAllocation.java:257)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:967)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:498)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:434)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:565)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at com.github.shadowsocks.net.HttpsTest$testConnection$1$1.invokeSuspend(HttpsTest.kt:101)
	at com.github.shadowsocks.net.HttpsTest$testConnection$1$1.invoke(Unknown Source:10)
	at com.github.shadowsocks.utils.UtilsKt$useCancellable$$inlined$suspendCancellableCoroutine$lambda$2.invokeSuspend(Utils.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by Mygod** [comment]
Report to your device vendor instead.

Additional information: (@madeye)
This seems to be a bug almost exclusive to Samsung phones (<1% also found in Meizu, Xiaomi, Infinix, and HUAWEI).
Workaround would be to include and ship an HTTP library in our apk and use that. Unfortunately, I have not found an HTTP nonblocking coroutines library yet. See also: https://github.com/ktorio/ktor/issues/1197

**Comment by madeye** [comment]
It looks an issue of okhttp library on specific devices? If so, we can do nothing here.

**Comment by DitFranXX** [comment]
Thank you for response.
But is possible to use try-catch for prevent app crashes? It's annoying...

**Comment by Mygod** [comment]
Please avoid using this feature until Samsung issues a fix. Using try-catch will not fix this issue. (in fact how are your phones even functioning at this point)

**Comment by DitFranXX** [comment]
I received some update from samsung.  They said Analysis was delayed.

It will fixed on next S/W update. They didn't say when it released.

**Comment by wfi-mitchgrogg** [comment]
@DitFranXX Could you provide a link to the issue you opened with Samsung (if it is public)? I would benefit from being able to monitor Samsung's progress toward fixing this bug.
