### ISSUE TITLE
app crash with exception

### ISSUE THREAD

**Issue by didi-droid** [shadowsocks/shadowsocks-android#2332]
Please read contributing guidelines. Thanks.

**Describe the bug**
点开服务器配置，应用闪退

**To Reproduce**
1. 打开app
2. 点开服务器配置
3. app闪退

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android 10
 - Device: xiaomi miui 11
 - Version: 4e23960088432e59164ced4847be5b7e722fa894
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: rc4-md5
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [x] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [x] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
```
androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.github.shadowsocks.ProfileConfigFragment: could not find Fragment constructor
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
 at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
 at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:402)
 at androidx.fragment.app.FragmentContainerView.onAttachedToWindow(FragmentContainerView.java:172)
 at android.view.View.dispatchAttachedToWindow(View.java:19601)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3452)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3459)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2089)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1782)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7785)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
 at android.view.Choreographer.doCallbacks(Choreographer.java:854)
 at android.view.Choreographer.doFrame(Choreographer.java:789)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:221)
 at android.app.ActivityThread.main(ActivityThread.java:7520)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NoSuchMethodException: com.github.shadowsocks.ProfileConfigFragment.<init> []
 at java.lang.Class.getConstructor0(Class.java:2332)
 at java.lang.Class.getConstructor(Class.java:1728)
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
 ... 25 more
```

**Comment by madeye** [comment]
Cannot reproduce on Android 10 emulator.

**Comment by didi-droid** [comment]
> Cannot reproduce on Android 10 emulator.

那我现在从哪方面帮你定位故障呢？

**Comment by Buffer2Disk** [comment]
@madeye  @Mygod  i can reproduce in xiaomi  Android 7.1.2 , by the way , tag 4.8.5 works fine , so maybe due to this commit  **Refine code style** like didi-droid said

**Comment by shadowsocksRb** [comment]
问题由 https://github.com/shadowsocks/shadowsocks-android/commit/4e23960088432e59164ced4847be5b7e722fa894 引入，AndroidX团队已取消此替换建议：https://issuetracker.google.com/issues/142601969#comment3 。

撤销修改直到aapt2支持，或添加keep规则。

**Comment by Mygod** [comment]
Nice. Thanks guy.

**Comment by runtimesmart** [comment]
> 问题由 [4e23960](https://github.com/shadowsocks/shadowsocks-android/commit/4e23960088432e59164ced4847be5b7e722fa894) 引入，AndroidX团队已取消此替换建议：https://issuetracker.google.com/issues/142601969#comment3 。
> 
> 撤销修改直到aapt2支持，或添加keep规则。

--------
this issue still exists in oneplus 7 android 10.

**Comment by madeye** [comment]
Let's wait for next release of aapt2.

**Comment by runtimesmart** [comment]
> Let's wait for next release of aapt2.

--------
found it.this issue occurs when you build release version,
so the proguard-rules.pro should be add :
`-keep class com.google.android.material.** {*;}
-keep class androidx.** {*;}
-keep public class * extends androidx.**
-keep interface androidx.** {*;}
-dontwarn com.google.android.material.**
-dontnote com.google.android.material.**
-dontwarn androidx.**`

to avoid the fragment being obfuscated.
