### ISSUE TITLE
jarsigner error:  RuntimeException: keystore load: (No such file or directory)

### ISSUE THREAD

**Issue by cloudtrends** [shadowsocks/shadowsocks-android#240]
hi,

There are one error when I do compile following readme in Mac :

( the keystore file exist and I had move it to  ~/.keystore ) , and modify local.properties file content according .

$sbt  android:package-release

jarsigner error: java.lang.RuntimeException: keystore load: XXXXX  (No such file or directory)
java.lang.RuntimeException: Error signing jar (exit code was 1.)
	at scala.sys.package$.error(package.scala:27)
	at sbt.SignJar$.execute(Pack.scala:75)
	at sbt.SignJar$.sign(Pack.scala:63)
	at android.Tasks$$anonfun$48$$anonfun$apply$59.apply(tasks.scala:762)
	at android.Tasks$$anonfun$48$$anonfun$apply$59.apply(tasks.scala:752)
	at scala.Option.map(Option.scala:145)
	at android.Tasks$$anonfun$48.apply(tasks.scala:752)
	at android.Tasks$$anonfun$48.apply(tasks.scala:746)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by madeye** [comment]
Check your config more carefully.
