### ISSUE TITLE
Support for standalone VR headsets

### ISSUE THREAD

**Issue by cyqsimon** [shadowsocks/shadowsocks-android#2479]
I recently bought an Oculus Go headset, which is an Android-powered standalone VR headset, but was disappointed to learn that Shadowsocks android does not run on the platform. For now I can just use a SS-driven proxy on a machine on the local network, but obviously this severely interferes with the headset's portability. Ideally I would like to run SS directly on my Go, so that I'm not tied down to a PC.

What I have tried:

Sideloading every build in release v5.0.5, including ones for Android TV. Nothing worked. The headset simply prompts "An error occurred, try again later" when I try to launch the app.

Also, if anyone had better luck installing SS on their VR headsets please advise.

**Comment by Mygod** [comment]
logcat

**Comment by cyqsimon** [comment]
> logcat

Will do tonight.

**Comment by cyqsimon** [comment]
Sorry for the delay. This is the all the lines from logcat that includes shadowsocks.

```
03-28 20:42:19.246   974   974 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package com.github.shadowsocks.tv
03-28 20:42:19.246   974   974 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.github.shadowsocks.tv because it was previously installed without
03-28 20:42:19.246   974   974 W PackageManager: Unknown permission com.google.android.c2dm.permission.RECEIVE in package com.github.shadowsocks.tv
03-28 20:42:19.246   974   974 W PackageManager: Unknown permission com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE in package com.github.shadowsocks.tv
03-28 20:42:19.246   974   974 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.github.shadowsocks.tv because it was previously installed without

03-28 20:43:48.191  2532  2554 I AppModule: LaunchAppWithCommand com.github.shadowsocks.tv 
03-28 20:43:48.203  1594  1659 D [OAR] PanelAppConfigurationUtil: Retrieving panel configuration for com.github.shadowsocks.tv - 
03-28 20:43:48.206  1594  1659 W System.err: java.lang.IllegalArgumentException: No default service found in application. Package com.github.shadowsocks.tv is not a valid Panel Service.
03-28 20:43:48.206  1594  1659 W System.err: 	at com.oculus.vrshell.util.PanelAppConfigurationUtil.buildPanelAppConfiguration(PanelAppConfigurationUtil.java:64)
03-28 20:43:48.207  1594  1659 W System.err: 	at com.oculus.vrshell.ShellApplication.getPanelAppConfiguration(ShellApplication.java:698)
03-28 20:43:48.207  1594  1659 W PanelUtil_JNI: JVM exception occurred: java.lang.IllegalArgumentException: No default service found in application. Package com.github.shadowsocks.tv is not a valid Panel Service. - com.github.shadowsocks.tv/
03-28 20:43:48.207  1594  1659 D [OAR] PanelAppConfigurationUtil: Retrieving panel configuration for com.github.shadowsocks.tv - 
03-28 20:43:48.213  1594  1659 W System.err: java.lang.IllegalArgumentException: No default service found in application. Package com.github.shadowsocks.tv is not a valid Panel Service.
03-28 20:43:48.213  1594  1659 W System.err: 	at com.oculus.vrshell.util.PanelAppConfigurationUtil.buildPanelAppConfiguration(PanelAppConfigurationUtil.java:64)
03-28 20:43:48.213  1594  1659 W System.err: 	at com.oculus.vrshell.ShellApplication.getPanelAppConfiguration(ShellApplication.java:698)
03-28 20:43:48.213  1594  1659 W PanelUtil_JNI: JVM exception occurred: java.lang.IllegalArgumentException: No default service found in application. Package com.github.shadowsocks.tv is not a valid Panel Service. - com.github.shadowsocks.tv/
03-28 20:43:48.216  1594  1659 I [OAR] SystemUXController: TV launch for com.github.shadowsocks.tv/com.github.shadowsocks.tv.MainActivity.
```

**Comment by cyqsimon** [comment]
Attempting to use ss-universal results in pretty much the same logs.

**Comment by Mygod** [comment]
Full logcat.

**Comment by kusty456** [comment]
> I recen- #- tly bought which is an Android-powered , but was disappointed to learn that Shadowsocks android does not run on the platform. For now I can just use a SS-driven proxy on a machine on the local network, but obviously this severely interferes with the  portability. Ideally I would like to run SS directly on my Go, so that I'm not tied down to a
> 
> What I have 
> 
> Sideloading every build in release v5.0.5, including ones for Android Nothing worked.  simply prompts "An  occurred, try again later" when I try to launch the app.
> `    _**@[]()[]()[]()[]()[]()**_`

**Comment by cyqsimon** [comment]
[logcat.log](https://github.com/shadowsocks/shadowsocks-android/files/4398347/logcat.log)

There

**Comment by Mygod** [comment]
Perhaps you need to install `com.oculus.tv`.

```
03-28 21:05:57.238  1594  1659 I [OAR] SystemUXController: com.oculus.tv is not installed. Redirecting to Store Page /item/1834973373242178.
```

**Comment by cyqsimon** [comment]
Will try that

**Comment by Mygod** [comment]
Closing due to inactivity.
