### ISSUE TITLE
shadowsocks-android项目中的shadowsocks-rust编译报错

### ISSUE THREAD

**Issue by janus-xiao** [shadowsocks/shadowsocks-android#2596]
2020-11-05T17:53:04.937+0800 [ERROR]  FAILURE: Build failed with an exception.
2020-11-05T17:53:04.938+0800 [ERROR] 
2020-11-05T17:53:04.938+0800 [ERROR]  * What went wrong:
2020-11-05T17:53:04.939+0800 [ERROR]  Execution failed for task ':core:cargoClean'.
2020-11-05T17:53:04.939+0800 [ERROR]  > A problem occurred starting process 'command 'cargo''
2020-11-05T17:53:04.939+0800 [ERROR] 
2020-11-05T17:53:04.940+0800 [ERROR]  * Try:
2020-11-05T17:53:04.940+0800 [ERROR]  Run with --scan to get full insights.
2020-11-05T17:53:04.941+0800 [ERROR] 
2020-11-05T17:53:04.941+0800 [ERROR]  * Exception is:
2020-11-05T17:53:04.941+0800 [ERROR]  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:cargoClean'.
2020-11-05T17:53:04.942+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:200)
2020-11-05T17:53:04.942+0800 [ERROR]  at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
2020-11-05T17:53:04.943+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:198)
2020-11-05T17:53:04.943+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
2020-11-05T17:53:04.943+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
2020-11-05T17:53:04.944+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2020-11-05T17:53:04.944+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
2020-11-05T17:53:04.945+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2020-11-05T17:53:04.945+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2020-11-05T17:53:04.945+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2020-11-05T17:53:04.946+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
2020-11-05T17:53:04.946+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
2020-11-05T17:53:04.946+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
2020-11-05T17:53:04.947+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2020-11-05T17:53:04.947+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2020-11-05T17:53:04.948+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2020-11-05T17:53:04.948+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2020-11-05T17:53:04.949+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2020-11-05T17:53:04.949+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2020-11-05T17:53:04.949+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2020-11-05T17:53:04.950+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2020-11-05T17:53:04.950+0800 [ERROR]  at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2020-11-05T17:53:04.950+0800 [ERROR]  at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2020-11-05T17:53:04.951+0800 [ERROR]  at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
2020-11-05T17:53:04.951+0800 [ERROR]  at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
2020-11-05T17:53:04.952+0800 [ERROR]  at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
2020-11-05T17:53:04.952+0800 [ERROR]  at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
2020-11-05T17:53:04.952+0800 [ERROR]  at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:35
2)
2020-11-05T17:53:04.953+0800 [ERROR]  at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:33
8)
2020-11-05T17:53:04.953+0800 [ERROR]  at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
2020-11-05T17:53:04.954+0800 [ERROR]  at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
2020-11-05T17:53:04.954+0800 [ERROR]  at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
2020-11-05T17:53:04.955+0800 [ERROR]  at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
2020-11-05T17:53:04.955+0800 [ERROR]  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2020-11-05T17:53:04.956+0800 [ERROR]  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2020-11-05T17:53:04.956+0800 [ERROR]  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2020-11-05T17:53:04.956+0800 [ERROR]  Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'cargo''
2020-11-05T17:53:04.957+0800 [ERROR]  at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
2020-11-05T17:53:04.957+0800 [ERROR]  at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
2020-11-05T17:53:04.958+0800 [ERROR]  at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
2020-11-05T17:53:04.958+0800 [ERROR]  at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
2020-11-05T17:53:04.958+0800 [ERROR]  at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
2020-11-05T17:53:04.959+0800 [ERROR]  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2020-11-05T17:53:04.959+0800 [ERROR]  at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2020-11-05T17:53:04.960+0800 [ERROR]  at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2020-11-05T17:53:04.960+0800 [ERROR]  Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'cargo'
2020-11-05T17:53:04.960+0800 [ERROR]  at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
2020-11-05T17:53:04.961+0800 [ERROR]  at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
2020-11-05T17:53:04.961+0800 [ERROR]  at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
2020-11-05T17:53:04.961+0800 [ERROR]  at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
2020-11-05T17:53:04.962+0800 [ERROR]  at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
2020-11-05T17:53:04.962+0800 [ERROR]  ... 4 more
2020-11-05T17:53:04.963+0800 [ERROR]  Caused by: java.io.IOException: Cannot run program "cargo" (in directory "G:\GithubSoftware\ShadowsocksAndroid\core\src\main\rust\shadowso
cks-rust"): CreateProcess error=2, 系统找不到指定的文件。
2020-11-05T17:53:04.963+0800 [ERROR]  at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
2020-11-05T17:53:04.963+0800 [ERROR]  ... 8 more
2020-11-05T17:53:04.964+0800 [ERROR]  Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
2020-11-05T17:53:04.964+0800 [ERROR]  ... 9 more

**Comment by janus-xiao** [comment]
路径配置没问题

**Comment by janus-xiao** [comment]
第二天打开AS这个问题消息了。。。
