### ISSUE TITLE
FireTV 6.2.7.7 use shadowsocks5.2.1(both tv version and normal version) libsslocal crash

### ISSUE THREAD

**Issue by jubaobleach** [shadowsocks/shadowsocks-android#2676]
Please read contributing guidelines. Thanks.
I use shadowsocks5.2.1 armv7a version download in release part
**Describe the bug**
02-11 22:03:08.555 16957 16957 F DEBUG   : Build fingerprint: 'Amazon/mantis/mantis:6.0/NS6277/3033N:user/amz-p,release-keys'
02-11 22:03:08.555 16957 16957 F DEBUG   : Revision: '0'
02-11 22:03:08.555 16957 16957 F DEBUG   : ABI: 'arm'
02-11 22:03:08.556 16957 16957 F DEBUG   : pid: 16935, tid: 16935, name: libsslocal.so  >>> /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so <<<
02-11 22:03:08.556 16957 16957 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-11 22:03:08.556 16957 16957 F DEBUG   :     r0 00000000  r1 00004227  r2 00000006  r3 00000008
02-11 22:03:08.556 16957 16957 F DEBUG   :     r4 a899c58c  r5 00000006  r6 a899c534  r7 0000010c
02-11 22:03:08.556 16957 16957 F DEBUG   :     r8 00000001  r9 0c91bb00  sl 0c94a640  fp bec21708
02-11 22:03:08.556 16957 16957 F DEBUG   :     ip 00000062  sp bec1d258  lr a88ad437  pc a88afc94  cpsr 200f0010
02-11 22:03:08.561 16957 16957 F DEBUG   : 
02-11 22:03:08.561 16957 16957 F DEBUG   : backtrace:
02-11 22:03:08.562 16957 16957 F DEBUG   :     #00 pc 00049c94  /system/lib/libc.so (tgkill+12)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #01 pc 00047433  /system/lib/libc.so (pthread_kill+34)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #02 pc 0001d6f5  /system/lib/libc.so (raise+10)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #03 pc 00019241  /system/lib/libc.so (__libc_android_abort+34)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #04 pc 00017200  /system/lib/libc.so (abort+4)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #05 pc 00146853  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #06 pc 0014684b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #07 pc 001d2967  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #08 pc 001d271d  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #09 pc 001e56ed  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #10 pc 001e568b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #11 pc 001e5651  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #12 pc 001e562f  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #13 pc 0007aeb1  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #14 pc 000a7e85  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #15 pc 00043e09  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #16 pc 000ab95b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.562 16957 16957 F DEBUG   :     #17 pc 00016e19  /system/lib/libc.so (__libc_init+48)
02-11 22:03:08.562 16957 16957 F DEBUG   :     #18 pc 00023348  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.574   611   750 W NativeCrashListener: Couldn't find ProcessRecord for pid 16935
02-11 22:03:08.582   611   628 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
02-11 22:03:08.583   198   198 W         : debuggerd: resuming target 16935
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: extractNativeCrashFromBody inputTrace=*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: Build fingerprint: 'Amazon/mantis/mantis:6.0/NS6277/3033N:user/amz-p,release-keys'
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: Revision: '0'
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: ABI: 'arm'
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: pid: 16935, tid: 16935, name: libsslocal.so  >>> /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so <<<
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     r0 00000000  r1 00004227  r2 00000006  r3 00000008
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     r4 a899c58c  r5 00000006  r6 a899c534  r7 0000010c
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     r8 00000001  r9 0c91bb00  sl 0c94a640  fp bec21708
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     ip 00000062  sp bec1d258  lr a88ad437  pc a88afc94  cpsr 200f0010
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d0  0000002463657375  d1  6464412068746977
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d2  726c612073736572  d3  206e692079646165
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d4  0000000000000000  d5  000002fc00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d6  0000009f00000014  d7  0000004700000062
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d8  0000000000000000  d9  0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d10 0000000000000000  d11 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d12 0000000000000000  d13 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d14 0000000000000000  d15 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d16 00000000085955d8  d17 00000000077d5d50
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d18 0000000008595588  d19 00000000077d5d28
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d20 0000000000000000  d21 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d22 0000000000000000  d23 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d24 0000000000000000  d25 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d26 0000000000000000  d27 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d28 0000000000000000  d29 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     d30 0000000000000000  d31 0000000000000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     scr 80000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: 
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: backtrace:
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #00 pc 00049c94  /system/lib/libc.so (tgkill+12)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #01 pc 00047433  /system/lib/libc.so (pthread_kill+34)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #02 pc 0001d6f5  /system/lib/libc.so (raise+10)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #03 pc 00019241  /system/lib/libc.so (__libc_android_abort+34)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #04 pc 00017200  /system/lib/libc.so (abort+4)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #05 pc 00146853  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #06 pc 0014684b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #07 pc 001d2967  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #08 pc 001d271d  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #09 pc 001e56ed  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #10 pc 001e568b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #11 pc 001e5651  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #12 pc 001e562f  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #13 pc 0007aeb1  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #14 pc 000a7e85  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #15 pc 00043e09  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #16 pc 000ab95b  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #17 pc 00016e19  /system/lib/libc.so (__libc_init+48)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #18 pc 00023348  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: 
02-11 22:03:08.584   611   628 V CrashDescriptorUtil: stack:
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d218  bec1d314  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d21c  0c836081  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d220  bec21708  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d224  0c8360b1  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d228  bec1d2d8  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d22c  bec1d314  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d230  00000003
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d234  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d238  0c9360c0  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d23c  00000001
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d240  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d244  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d248  0c91bb00  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d24c  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d250  a899c58c
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d254  a88ad427  /system/lib/libc.so (pthread_kill+22)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #00  bec1d258  00001204
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          ........  ........
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #01  bec1d258  00001204
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d25c  00000006
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d260  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d264  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d268  0c94a708  /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d26c  a88836f9  /system/lib/libc.so (raise+14)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #02  bec1d270  bec1d28c  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d274  a887f245  /system/lib/libc.so (__libc_android_abort+38)
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:     #03  bec1d278  00000000
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d27c  bec1d284  [stack]
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d280  00000003
02-11 22:03:08.584   611   628 V CrashDescriptorUtil:          bec1d
02-11 22:03:08.589   611   628 I CrashDescriptorUtil: addErrorToCommonLog Hash already present in file
02-11 22:03:08.591   611   628 E SELinux : avc:  denied  { log_internal_metric } for  scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:system_server:s0 tclass=amazon_policies permissive=0
02-11 22:03:08.592 15842 15842 W GuardedProcessPool$Guard: error occurred. stop guard: /data/app/com.github.shadowsocks-1/lib/arm/libsslocal.so --stat-path /data/user_de/0/com.github.shadowsocks/no_backup/stat_main -c /data/user/0/com.github.shadowsocks/no_backup/shadowsocks.conf --udp-bind-addr 127.0.0.1:1080 --vpn -U --dns-addr 127.0.0.1:5450 --local-dns-addr local_dns_path --remote-dns-addr dns.google:53 --acl /data/user_de/0/com.github.shadowsocks/no_backup/bypass-lan-china.acl
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: java.io.IOException: libsslocal exits too fast (exit code: 134)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at com.github.shadowsocks.bg.GuardedProcessPool$Guard.looper(GuardedProcessPool.kt:75)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at com.github.shadowsocks.bg.GuardedProcessPool$Guard$looper$1.invokeSuspend(GuardedProcessPool.kt)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at android.os.Handler.handleCallback(Handler.java:751)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at android.os.Looper.loop(Looper.java:154)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at android.app.ActivityThread.main(ActivityThread.java:6194)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at java.lang.reflect.Method.invoke(Native Method)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
02-11 22:03:08.593 15842 15842 W BaseService$Interface$onStartCommand: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
02-11 22:03:08.600   611   611 W TelecomManager: Telecom Service not found.

**To Reproduce**

click the vpn start button and crash every time.

1. Go to '...' ≈

**Expected behavior**

**Screenshots**
it say libsslocal exit too fast and exit code is 134.
I saw the code here, and get adb info above.
![image](https://user-images.githubusercontent.com/58602/107649330-532a5e80-6cb8-11eb-9cfb-415acfb1d0ef.png)

**Smartphone (please complete the following information):**
amazon  FireTV 4k  version 6.2.7.7 

**Configuration**
Put an `x` inside the [ ] that applies.

* [X] IPv4 server address
* [ ] IPv6 server address
* [X] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method: CHACHA20-IETF-POLY1305 
* Route
  * [X] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable): no plugin
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by jubaobleach** [comment]
I read the code and move it to https://github.com/shadowsocks/shadowsocks-rust/issues/420
