### ISSUE TITLE
Android App Bundle  .aab  file error

### ISSUE THREAD

**Issue by myflyingfish** [shadowsocks/shadowsocks-android#2747]
Please read contributing guidelines. Thanks.

**Describe the bug**
when use App bundle . connect error,

**To Reproduce**
1 use App bundle 
2 connect 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
xiaomi 6 

**Configuration**
Put an `x` inside the [ ] that applies.
* If you're not using VPN mode, please supply more details here:
*

Non-fatal Exception: java.io.IOException
Cannot run program "/data/app/com.**********.vpn-OX3nURyLvUlamexjuE5czA==/lib/arm64/libsslocal.so" (in directory "/data/user_de/0/com.**********vpn/no_backup"): error=2, No such file or directory

Caused by java.io.IOException: error=2, No such file or directory
       at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java)
       at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
       at java.lang.ProcessImpl.start(ProcessImpl.java:141)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
       at com.github.shadowsocks.bg.GuardedProcessPool$Guard.start(SourceFile:54)
       at com.github.shadowsocks.bg.GuardedProcessPool.start(SourceFile:117)
       at com.github.shadowsocks.bg.GuardedProcessPool.start$default(SourceFile:114)
       at com.github.shadowsocks.bg.ProxyInstance.start(SourceFile:124)
       at com.github.shadowsocks.bg.ProxyInstance.start$default(SourceFile:68)
       at com.github.shadowsocks.bg.BaseService$Interface$DefaultImpls.startProcesses(SourceFile:239)
       at com.github.shadowsocks.bg.VpnService.startProcesses(SourceFile:161)
       at com.github.shadowsocks.bg.BaseService$Interface$onStartCommand$3.invokeSuspend(SourceFile:383)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
       at kotlinx.coroutines.DispatchedTask.run(SourceFile:106)
       at android.os.Handler.handleCallback(Handler.java:914)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7564)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by myflyingfish** [comment]
who can help me
