### ISSUE TITLE
aab can't find libsslocal.so 

### ISSUE THREAD

**Issue by Jmkery** [shadowsocks/shadowsocks-android#2763]
Please read contributing guidelines. Thanks.

**Describe the bug**
When I build this app by *.aab. It will crash in thread of "com.github.shadowsocks.bg". But when I run this app by *.apk, it will not happen

**To Reproduce**
1. Go to 'home'
2. Click on 'connect'
3. It will crash.

**Expected behavior**
I hope it will connect success as same as *.apk

**Screenshots**

**Smartphone (please complete the following information):**
 - Android OS version: [10]
 - Device: [any device by arm64]
 - Version: [v5.2.5 or lower]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ x] IPv4 server address
* [ ] IPv6 server address
* [ x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**
I hope can reply soon , thx:)

**Comment by Jmkery** [comment]
logcat:
W/BaseService$Interface$onStartCommand: java.io.IOException: Cannot run program "/data/app/com.github.shadowsocks-rCssd9K6mbPMGyyWJxXG8A==/lib/arm64/libsslocal.so" (in directory "/data/user_de/0/com.github.shadowsocks/no_backup"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at com.github.shadowsocks.bg.GuardedProcessPool$Guard.start(GuardedProcessPool.kt:54)
        at com.github.shadowsocks.bg.GuardedProcessPool.start(GuardedProcessPool.kt:117)
        at com.github.shadowsocks.bg.GuardedProcessPool.start$default(GuardedProcessPool.kt:114)
        at com.github.shadowsocks.bg.ProxyInstance.start(ProxyInstance.kt:116)
        at com.github.shadowsocks.bg.ProxyInstance.start$default(ProxyInstance.kt:60)
        at com.github.shadowsocks.bg.BaseService$Interface$DefaultImpls.startProcesses(BaseService.kt:238)
        at com.github.shadowsocks.bg.VpnService.startProcesses(VpnService.kt:157)
        at com.github.shadowsocks.bg.BaseService$Interface$onStartCommand$3.invokeSuspend(BaseService.kt:367)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7868)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at com.github.shadowsocks.bg.GuardedProcessPool$Guard.start(GuardedProcessPool.kt:54) 
        at com.github.shadowsocks.bg.GuardedProcessPool.start(GuardedProcessPool.kt:117) 
        at com.github.shadowsocks.bg.GuardedProcessPool.start$default(GuardedProcessPool.kt:114) 
        at com.github.shadowsocks.bg.ProxyInstance.start(ProxyInstance.kt:116) 
        at com.github.shadowsocks.bg.ProxyInstance.start$default(ProxyInstance.kt:60) 
        at com.github.shadowsocks.bg.BaseService$Interface$DefaultImpls.startProcesses(BaseService.kt:238) 
        at com.github.shadowsocks.bg.VpnService.startProcesses(VpnService.kt:157) 
        at com.github.shadowsocks.bg.BaseService$Interface$onStartCommand$3.invokeSuspend(BaseService.kt:367) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:230) 
        at android.app.ActivityThread.main(ActivityThread.java:7868) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
