### ISSUE TITLE
App crashed when import profile by click any ss:// link. (tested with 5.2.4 and 5.2.5)

### ISSUE THREAD

**Issue by 297925723c1851b758fed27952735557** [shadowsocks/shadowsocks-android#2803]
com.github.shadowsocks E/AndroidRuntime: FATAL EXCEPTION: main

`    java.lang.IllegalArgumentException: com.google.android.material.dialog.MaterialAlertDialogBuilder requires a value for the com.github.shadowsocks:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
        at com.google.android.material.resources.MaterialAttributes.resolveOrThrow(MaterialAttributes.java:69)
        at com.google.android.material.color.MaterialColors.getColor(MaterialColors.java:66)
        at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:120)
        at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:103)
        at com.github.shadowsocks.plugin.fragment.AlertDialogFragment.onCreateDialog(AlertDialogFragment.kt:66)
        at com.github.shadowsocks.plugin.fragment.AlertDialogFragment.onCreateDialog(AlertDialogFragment.kt:37)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:644)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:558)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
`

**Comment by Mygod** [comment]
Ah so that's how you reproduce the crashes. Thanks!

**Comment by 297925723c1851b758fed27952735557** [comment]
> Ah so that's how you reproduce the crashes. Thanks!

tested with a simple html file, it crashes.
`<a href='ss://***base64encode****'> import </a>`
