### ISSUE TITLE
Shadowsocks crashes from time to time

### ISSUE THREAD

**Issue by twilightgod** [shadowsocks/shadowsocks-android#313]
Android 4.4.4 Sony Xperia Z Ultra

3C Toolbox Pro (logcat)
======================
W/08:28:00.921 GoogleTagManager(28777)
	at java.lang.Thread.run(Thread.java:841)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/08:28:00.921 GoogleTagManager(28777)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/08:28:00.921 GoogleTagManager(28777)
	at com.google.android.gms.tagmanager.co.run(Unknown Source)
W/08:28:00.921 GoogleTagManager(28777)
	at com.google.android.gms.tagmanager.co.qe(Unknown Source)
W/08:28:00.921 GoogleTagManager(28777)
	at com.google.android.gms.tagmanager.aw.cF(Unknown Source)
W/08:28:00.921 GoogleTagManager(28777)
	at com.google.android.gms.tagmanager.aw.a(Unknown Source)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.Connection.connect(Connection.java:101)
W/08:28:00.921 GoogleTagManager(28777)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:131)
W/08:28:00.921 GoogleTagManager(28777)
	at java.net.Socket.connect(Socket.java:838)
W/08:28:00.921 GoogleTagManager(28777)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
W/08:28:00.921 GoogleTagManager(28777)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/08:28:00.921 GoogleTagManager(28777)
	at libcore.io.IoBridge.connect(IoBridge.java:116)
W/08:28:00.921 GoogleTagManager(28777)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:163)
W/08:28:00.921 GoogleTagManager(28777)
java.net.SocketTimeoutException: failed to connect to www.googletagmanager.com/74.125.68.97 (port 443) after 20000ms
W/08:28:00.921 GoogleTagManager(28777)
Error when loading resources from url: https://www.googletagmanager.com/r?id=GTM-NT8WS8&v=a65833898&pv=Mzk$0 failed to connect to www.googletagmanager.com/74.125.68.97 (port 443) after 20000ms
W/08:27:20.501 GoogleTagManager(28777)
IOException getting Ad Id Info
D/08:27:20.481 dalvikvm(28777)
VFY: replacing opcode 0x6e at 0x000d
W/08:27:20.481 dalvikvm(28777)
VFY: unable to resolve virtual method 580: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
I/08:27:20.481 dalvikvm(28777)
Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method com.github.shadowsocks.ShadowsocksNatService.setDnsForAllNetwork
D/08:27:20.481 dalvikvm(28777)
VFY: replacing opcode 0x6e at 0x0008
W/08:27:20.481 dalvikvm(28777)
VFY: unable to resolve virtual method 580: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
I/08:27:20.481 dalvikvm(28777)
Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method com.github.shadowsocks.ShadowsocksNatService.restoreDnsForAllNetwork
W/08:27:20.461 dalvikvm(28777)
VFY: unable to find class referenced in signature (Landroid/net/Network;)
D/08:27:20.461 dalvikvm(28777)
VFY: replacing opcode 0x6e at 0x0010
W/08:27:20.461 dalvikvm(28777)
VFY: unable to resolve virtual method 580: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
I/08:27:20.461 dalvikvm(28777)
Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method com.github.shadowsocks.ShadowsocksNatService.flushDns
W/08:27:20.441 GoogleTagManager(28777)
Failed to extract the container from the resource file. Resource is a UTF-8 encoded string but doesn't contain a JSON container

**Comment by twilightgod** [comment]
2.6.8

**Comment by twilightgod** [comment]
.

**Comment by madeye** [comment]
It'd be an issue of your ROM. Try some other ones.
