### ISSUE TITLE
OnePlus 12 (Android 15) Unable to resolve host "cp.cloudflare.com": No address associated with hostname, and the sslocal last exit code: 134

### ISSUE THREAD

**Issue by chuuuevi** [shadowsocks/shadowsocks-android#3185]
**Describe the bug**
1. Unable to resolve host "cp.cloudflare.com": No address associated with hostname
2. adb logcat report: "sslocal last exit code: 134"

**Smartphone (please complete the following information):**
 - Android OS version: Android 15 (ColorOS 15)
 - Android OS kernel version: 6.1.75-android14-11-0-g9a3d0e631104
 - System OS version: PJD110-_15.0.0.206(CN01U140P02)
 - Device: OnePlus 12
 - shadowsocks-android Version: 5.3.4
 - v2ray-plugin-android Version: 1.3.3

**Configuration**
Put an `x` inside the [ ] that applies.

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [x] All
  * [x] Bypass LAN
  * [x] Bypass China
  * [x] Bypass LAN & China
  * [x] GFW List
  * [x] China List
  * [x] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [x] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by chuuuevi** [comment]
adb logcat|grep shadowsocks

```
11-19 11:25:12.684  3039  3039 E OPLUS_KEVENT_RECORD: OPLUS_KEVENT payload:10450,path@@/data/app/~~9fPczTGGOw9hjcCKWnqkJQ==/com.github.shadowsocks-oxmac2nAkMdpr50KPzrY1Q==/lib/arm64/libsslocal.so
11-19 11:25:15.690  3039  3039 E OPLUS_KEVENT_RECORD: OPLUS_KEVENT payload:10450,path@@/data/app/~~9fPczTGGOw9hjcCKWnqkJQ==/com.github.shadowsocks-oxmac2nAkMdpr50KPzrY1Q==/lib/arm64/libsslocal.so
11-19 11:25:15.693 23630 23630 W GuardedProcessPool$Guard: 	at com.github.shadowsocks.bg.GuardedProcessPool$Guard.looper(GuardedProcessPool.kt:78)
11-19 11:25:15.693 23630 23630 W GuardedProcessPool$Guard: 	at com.github.shadowsocks.bg.GuardedProcessPool$Guard$looper$1.invokeSuspend(GuardedProcessPool.kt:0)
11-19 11:25:15.694 23630 23630 I GuardedProcessPool$Guard: restart process: /data/app/~~9fPczTGGOw9hjcCKWnqkJQ==/com.github.shadowsocks-oxmac2nAkMdpr50KPzrY1Q==/lib/arm64/libsslocal.so --stat-path /data/user_de/0/com.github.shadowsocks/no_backup/stat_main -c /data/user/0/com.github.shadowsocks/no_backup/shadowsocks.conf --vpn (last exit code: 134)
```

**Comment by yanickxia** [comment]
use `kcptun` plugin same problem

**Comment by zod076** [comment]
I have the same problem on an Android 12 Tablet. Unable to resolve the cp.cloudflare.com domain. The tablet is connected to an IPv6-only wifi. For Server address, I've tried using hostname as an IPv6 address enclosed in brackets, still no go.

**Comment by yakeworld** [comment]
1. 服务器不要采用域名，采用ip地址
这个可能是最关键步骤。
3. IPV6路由可以尝试开启和关闭
4. 远程DNS可以更换不同的DNS。

纯血鸿蒙系统支持运行。

**Comment by Mygod** [comment]
@zonyitoo I can reproduce this issue. Shadowsocks server name must always be resolved via local DNS if provided, otherwise it will just be a dead loop. Any thoughts?

**Comment by zonyitoo** [comment]
An easy and straight forward solution for verify: set `SS_SYSTEM_DNS_RESOLVER_FORCE_BUILTIN=1` environment variable when starting `sslocal` process. `sslocal` won't use `hickory-dns` but tokio's builtin DNS, which is `getaddrinfo` on Android/Linux.

**Comment by zonyitoo** [comment]
If servers' name were resolved by `getinfoaddr`, which is "Local DNS" resolver, why it still triggered dead loop?

1. Are you running the latest shadowsocks-rust version? If no, try again with the latest version.
2. Packets sent by `getaddrinfo` may be routed back to VpnService, right? Because `getaddrinfo`'s socket didn't set `SO_MARK`.
    - If that is true, set a `dns` or `nameserver` in configuration to let `sslocal` uses hickory-dns resolver, which will create sockets with `SO_MARK` and `fd`s provided by `vpn_protect_path`.

If `dns` is set and everything works fine, then we should find a way to fix `/etc/resolv.conf` is missing on Android, which will allow creating hickory-dns resolver instance.

**Comment by Mygod** [comment]
@zonyitoo sslocal should *never* use built in DNS. That would result in sending the DNS query over default network, which is VPN, causing infinite loop. Only packets sent through `local_dns_addr` (which will be routed to JVM) will be automatically bypassed.

shadowsocks-android always provide both `local_dns_addr` and `remote_dns_addr` so it is not necessary to use `/etc/resolv.conf`.

**Comment by zonyitoo** [comment]
Ah.. I see. Then try to set `dns` with the same value of `local_dns_addr`, which should work.

**Comment by Mygod** [comment]
Why have two options for dns?

This definitely worked properly at some point (before v1.15).

**Comment by zonyitoo** [comment]
> Why have two options for dns?

`local_dns_addr` and `remove_dns_addr` is for `local-dns` instance, which is an independent local service.

`dns` is for the DNS resolver.

> This definitely worked properly at some point (before v1.15).

It was quite a long time. I did a refactor at some point that separates all local services into different standalone parts.

**Comment by zonyitoo** [comment]
BTW, consider upgrade `sslocal` to the latest version, many bugs are fixes since v1.15. Many. @Mygod

**Comment by Mygod** [comment]
Okay I reverted this change (https://github.com/shadowsocks/shadowsocks-android/commit/54dcbcec8df00536608d4ae188ff9ab35571719e#diff-835c30b997a2ddf9bc71aba62d5bf8882e0001b4d45edd148dcbf0323d63775eL73) but the DNS packet is still being sent over the VPN tunnel.

P.S. This is running latest rust.

**Comment by Mygod** [comment]
The behavior seems to be the same with either setting.

**Comment by zonyitoo** [comment]
When `dns` is set with `unix://` prefix, DNS resolver will be set as `LocalDns`: https://github.com/shadowsocks/shadowsocks-rust/blob/c9f47c6db3b9174923504d753d7df682c1b4f9ea/crates/shadowsocks-service/src/config.rs#L2481-L2488 .

`LocalDns` is the same structure as the local dns service: https://github.com/shadowsocks/shadowsocks-rust/blob/c9f47c6db3b9174923504d753d7df682c1b4f9ea/crates/shadowsocks-service/src/dns/mod.rs#L79-L92

**Comment by Mygod** [comment]
DEBUG logs shows that the server name query is still being sent through `shadowsocks_service::local::dns::server` from `acl_lookup`. This cannot be the correct behavior?

**Comment by zonyitoo** [comment]
Did service listening on `unix://local_dns_path` received the DNS query?

**Comment by zonyitoo** [comment]
> DEBUG logs shows that the server name query is still being sent through `shadowsocks_service::local::dns::server` from `acl_lookup`. This cannot be the correct behavior?

So DNS query is sent back to `sslocal`'s `local-dns` port?

**Comment by zonyitoo** [comment]
Do you have any Plugins running?

**Comment by Mygod** [comment]
`TRACE main ThreadId(01) shadowsocks_service::dns: shadowsocks-rust/crates/shadowsocks-service/src/dns/mod.rs:84: initializing direct DNS resolver for local_dns_path `

Trace logs also show that the DNS resolver was correctly initialized. It appears that it was also initially used for resolving the server name.

I think the issue might be coming from load balancer. The problematic DNS lookup queries occurred only after this log: `shadowsocks_service::local::loadbalancing::ping_balancer: crates/shadowsocks-service/src/local/loadbalancing/ping_balancer.rs:132: init chose TCP server ...`

**Comment by Mygod** [comment]
Surely the load balancer should not be used if there's only one server??

**Comment by zonyitoo** [comment]
> Surely the load balancer should not be used if there's only one server??

Yes.

**Comment by zonyitoo** [comment]
Couldn't reproduce. No extra DNS queries could be found locally.

Looking further in your log:

```
## local-dns received 2 queries, A and AAAA for mtalk.google.com
4475-4567  LocalDnsWorker$accept   W  Received query A <server name>   ## local-dns's remote query for A mtalk.google.com
4475-4574  LocalDnsWorker$accept   W  Received query AAAA <server name>   ## local-dns's remote query for A mtalk.google.com
4475-4659  LocalDnsWorker$accept   W  Received query A mtalk.google.com  ## local-dns's local query for A mtalk.google.com
4475-4658  LocalDnsWorker$accept   W  Received query AAAA A mtalk.google.com  ## local-dns's local-query for AAAA mtalk.google.com?? But why AAAA, A
4475-4567  LocalDnsWorker$accept   W  Received query A <server name>  ## local-dns's remote query for AAAA mtalk.google.com
4475-4574  LocalDnsWorker$accept   W  Received query AAAA <server name> ## local-dns's remote query for AAAA mtalk.google.com
```

**Comment by Mygod** [comment]
```
DEBUG main ThreadId(01) shadowsocks_service::local::dns::server: DNS lookup AAAA <server name>.
 0: std::backtrace_rs::backtrace::libunwind::trace
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
 1: std::backtrace_rs::backtrace::trace_unsynchronized
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
 2: std::backtrace::Backtrace::create
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/backtrace.rs:331:13
 3: shadowsocks_service::local::dns::server::DnsClient::acl_lookup::{{closure}}
           at shadowsocks-rust/crates/shadowsocks-service/src/local/dns/server.rs:785:79
 4: shadowsocks_service::local::dns::server::DnsClient::resolve::{{closure}}
           at shadowsocks-rust/crates/shadowsocks-service/src/local/dns/server.rs:751:96
 5: shadowsocks_service::local::dns::server::DnsUdpServer::handle_udp_packet::{{closure}}
           at shadowsocks-rust/crates/shadowsocks-service/src/local/dns/server.rs:475:88
 6: <core::pin::Pin<P> as core::future::future::Future>::poll
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
 7: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:331:17
 8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/loom/std/unsafe_cell.rs:16:9
 9: tokio::runtime::task::core::Core<T,S>::poll
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:320:13
10: tokio::runtime::task::harness::poll_future::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:532:19
11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
12: std::panicking::try::do_call
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40
13: __rust_try
14: std::panicking::try
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19
15: std::panic::catch_unwind
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
16: tokio::runtime::task::harness::poll_future
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
18: tokio::runtime::task::harness::Harness<T,S>::poll
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:15
19: tokio::runtime::task::raw::poll
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:271:5
20: tokio::runtime::task::raw::RawTask::poll
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
21: tokio::runtime::task::LocalNotified<S>::run
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:463:9
22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:780:25
23: tokio::task::coop::with_budget
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/task/coop/mod.rs:167:5
24: tokio::task::coop::budget
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/task/coop/mod.rs:133:5
25: tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:368:43
26: tokio::runtime::scheduler::current_thread::Context::enter
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:432:19
27: tokio::runtime::scheduler::current_thread::Context::run_task
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:368:23
28: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:776:35
29: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:820:68
30: tokio::runtime::context::scoped::Scoped<T>::set
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context/scoped.rs:40:9
31: tokio::runtime::context::set_scheduler::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context.rs:180:26
32: std::thread::local::LocalKey<T>::try_with
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:310:12
33: std::thread::local::LocalKey<T>::with
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:274:15
34: tokio::runtime::context::set_scheduler
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context.rs:180:9
35: tokio::runtime::scheduler::current_thread::CoreGuard::enter
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:820:27
36: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:720:19
37: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:200:28
38: tokio::runtime::context::runtime::enter_runtime
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/context/runtime.rs:65:16
39: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/scheduler/current_thread/mod.rs:188:9
40: tokio::runtime::runtime::Runtime::block_on_inner
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/runtime.rs:368:47
41: tokio::runtime::runtime::Runtime::block_on
           at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/runtime.rs:340:13
42: shadowsocks_rust::service::local::main::{{closure}}
           at shadowsocks-rust/src/service/local.rs:1044:58
43: core::result::Result<T,E>::and_then
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1353:22
44: shadowsocks_rust::service::local::main
           at shadowsocks-rust/src/service/local.rs:1044:11
45: sslocal::main
           at shadowsocks-rust/bin/sslocal.rs:19:5
46: core::ops::function::FnOnce::call_once
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
47: std::sys::backtrace::__rust_begin_short_backtrace
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
48: std::rt::lang_start::{{closure}}
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:199:18
49: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/ops/function.rs:284:13
50: std::panicking::try::do_call
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:587:40
51: std::panicking::try
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:550:19
52: std::panic::catch_unwind
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panic.rs:358:14
53: std::rt::lang_start_internal::{{closure}}
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/rt.rs:168:24
54: std::panicking::try::do_call
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:587:40
55: std::panicking::try
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:550:19
56: std::panic::catch_unwind
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panic.rs:358:14
57: std::rt::lang_start_internal
           at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/rt.rs:164:5
58: std::rt::lang_start
           at ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:198:5
59: main
60: __libc_init
```

**Comment by Mygod** [comment]
It seems like the query was immediately sent to UDP endpoint? Maybe this has something to do with plugins?

**Comment by zonyitoo** [comment]
Yes. Could you try to run without plugin?

**Comment by Mygod** [comment]
Without plugins, the problematic `DNS lookup` logs disappeared but connection still not working...

**Comment by zonyitoo** [comment]
Could you see any logs like:

https://github.com/shadowsocks/shadowsocks-rust/blob/34ebd07a4d5c275fd741dc7b520c17a23fd493bb/crates/shadowsocks/src/dns_resolver/resolver.rs#L365-L367

> `trace!("DNS resolved {}:{} with customized", self.addr, self.port);`

https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks/src/dns_resolver/mod.rs#L142

> `trace!("trying connect {}:{} {}", $addr, $port, $resolved_addr);`

**Comment by Mygod** [comment]
Okay it looks like my IPv6 network was not working for some reason. Now domain name works without plugins.

**Comment by Mygod** [comment]
So this should work even with plugins, right? I thought we have resolved this in #2722.

**Comment by Mygod** [comment]
According to #2722, this line should be hit for plugins to work but it never seems to fire:

https://github.com/shadowsocks/shadowsocks-rust/blob/34ebd07a4d5c275fd741dc7b520c17a23fd493bb/crates/shadowsocks-service/src/local/dns/server.rs#L601

**Comment by zonyitoo** [comment]
So this commit actually fixes this issue? If true, I would make a new release with these changes.

**Comment by Mygod** [comment]
Yep.

**Comment by madeye** [comment]
Create a new release?

**Comment by Mygod** [comment]
Sure.

**Comment by luckypickle** [comment]
i also meet this problem.
my phone is oppo find x8s+ 
os is Android 15 (ColorOS 15)
when i use lastest commit to build self apk. i also meet this problem
the fllower is adb logcat 


pid: 32037, tid: 32037, name: libsslocal.so  >>> /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so <<<
      #01 pc 00000000004efd50  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #02 pc 00000000004efdb0  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #03 pc 0000000000513788  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #04 pc 00000000003874ec  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #05 pc 00000000004efda4  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #06 pc 00000000004ef260  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #07 pc 000000000051e590  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #08 pc 000000000051e530  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #09 pc 0000000000520c74  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #10 pc 00000000002b2a30  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #11 pc 00000000001df758  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #12 pc 0000000000236aa4  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #13 pc 0000000000253ebc  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #14 pc 0000000000206764  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
      #15 pc 0000000000255cd8  /data/app/~~OPaIk9W3wE6EspcGrUig8A==/com.github.shadowsocks-TQHxhfeAJ0J_jejDSs7fHw==/lib/arm64/libsslocal.so
java.io.IOException: libsslocal unexpectedly exits with code 134
	at com.github.shadowsocks.bg.GuardedProcessPool$Guard.looper(GuardedProcessPool.kt:78)
	at com.github.shadowsocks.bg.GuardedProcessPool$Guard$looper$1.invokeSuspend(GuardedProcessPool.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:288)
	at android.os.Looper.loop(Looper.java:393)
	at android.app.ActivityThread.main(ActivityThread.java:9529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)

**Comment by luckypickle** [comment]
i also meet this problem.
when i upgrade ssserver,
i also need reinstall kcptun v1.0.1 pre-release [kcptun-arm64-v8a-1.0.1.apk](https://github.com/shadowsocks/kcptun-android/releases/download/v1.0.1/kcptun-arm64-v8a-1.0.1.apk) .then i can use my shadowsocks
