### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by heiybb** [shadowsocks/shadowsocks-android#385]
It's my first time to build such a project,it seems that i meet some problem,but can't handle it,please help me.
I have already install build-tools 23.0.1,so i can not understand what the error means:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /root/Desktop/ss/project
[info] Set current project to shadowsocks (in build file:/root/Desktop/ss/)
[success] Total time: 1 s, completed 10-Oct-2015 21:37:32
[info] Updating {file:/root/Desktop/ss/}ss...
[info] Resolving com.nostra13.universalimageloader#universal-image-loader;1.8.4 [info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.android.support:support-v4:22.2.0 -> 23.0.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Unpacking aar: menudrawer-3.0.6.aar to net.simonvt.menudrawer-menudrawer-3.0.6
[info] Unpacking aar: play-services-base-8.1.0.aar to com.google.android.gms-play-services-base-8.1.0
[info] Unpacking aar: play-services-basement-8.1.0.aar to com.google.android.gms-play-services-basement-8.1.0
[info] Unpacking aar: play-services-ads-8.1.0.aar to com.google.android.gms-play-services-ads-8.1.0
[info] Unpacking aar: play-services-appindexing-8.1.0.aar to com.google.android.gms-play-services-appindexing-8.1.0
[info] Unpacking aar: play-services-analytics-8.1.0.aar to com.google.android.gms-play-services-analytics-8.1.0
[info] Unpacking aar: support-v4-23.0.1.aar to com.android.support-support-v4-23.0.1
[info] Unpacking aar: snackbar-0.5.0.aar to com.github.mrengineer13-snackbar-0.5.0
[info] Collecting resources
[info] Performing full resource merge
java.io.IOException: Cannot run program "/usr/Linux/android-sdk-linux/build-tools/23.0.1/aidl": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
	at android.Tasks$$anonfun$47$$anonfun$apply$56.apply(tasks.scala:703)
	at android.Tasks$$anonfun$47$$anonfun$apply$56.apply(tasks.scala:692)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at android.Tasks$$anonfun$47.apply(tasks.scala:692)
	at android.Tasks$$anonfun$47.apply(tasks.scala:683)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
	at android.Tasks$$anonfun$47$$anonfun$apply$56.apply(tasks.scala:703)
	at android.Tasks$$anonfun$47$$anonfun$apply$56.apply(tasks.scala:692)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at android.Tasks$$anonfun$47.apply(tasks.scala:692)
	at android.Tasks$$anonfun$47.apply(tasks.scala:683)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
/root/Desktop/ss/target/android/intermediates/aars/com.google.android.gms-play-services-base-8.1.0/res/drawable-mdpi/common_signin_btn_icon_normal_dark.9.png: Error: com.android.ide.common.process.ProcessException: 
	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:134)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
	at android.Resources$.fullResourceMerge(resources.scala:188)
	at android.Resources$.android$Resources$$merge$1(resources.scala:105)
	at android.Resources$.incrResourceMerge(resources.scala:110)
	at android.Resources$$anonfun$doCollectResources$7.apply(resources.scala:92)
	at android.Resources$$anonfun$doCollectResources$7.apply(resources.scala:90)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at android.Resources$.doCollectResources(resources.scala:95)
	at android.Tasks$$anonfun$34.apply(tasks.scala:466)
	at android.Tasks$$anonfun$34.apply(tasks.scala:464)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: /root/Desktop/ss/target/android/intermediates/aars/com.google.android.gms-play-services-base-8.1.0/res/drawable-mdpi/common_signin_btn_icon_normal_dark.9.png: Error: com.android.ide.common.process.ProcessException: 
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:116)
	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:50)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:134)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
	at android.Resources$.fullResourceMerge(resources.scala:188)
	at android.Resources$.android$Resources$$merge$1(resources.scala:105)
	at android.Resources$.incrResourceMerge(resources.scala:110)
	at android.Resources$$anonfun$doCollectResources$7.apply(resources.scala:92)
	at android.Resources$$anonfun$doCollectResources$7.apply(resources.scala:90)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at android.Resources$.doCollectResources(resources.scala:95)
	at android.Tasks$$anonfun$34.apply(tasks.scala:466)
	at android.Tasks$$anonfun$34.apply(tasks.scala:464)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: /root/Desktop/ss/target/android/intermediates/aars/com.google.android.gms-play-services-base-8.1.0/res/drawable-mdpi/common_signin_btn_icon_normal_dark.9.png: Error: com.android.ide.common.process.ProcessException: 
	at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:117)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:204)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ide.common.internal.PngException: com.android.ide.common.process.ProcessException: 
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:79)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ide.common.process.ProcessException: 
	at com.android.ide.common.process.ProcessResultImpl.rethrowFailure(ProcessResultImpl.java:60)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:77)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/usr/Linux/android-sdk-linux/build-tools/23.0.1/aapt": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.android.ide.common.process.DefaultProcessExecutor.execute(DefaultProcessExecutor.java:70)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:75)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at com.android.ide.common.process.DefaultProcessExecutor.execute(DefaultProcessExecutor.java:70)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:75)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (android:aidl) java.io.IOException: Cannot run program "/usr/Linux/android-sdk-linux/build-tools/23.0.1/aidl": error=2, No such file or directory
[error] (android:collectResources) /root/Desktop/ss/target/android/intermediates/aars/com.google.android.gms-play-services-base-8.1.0/res/drawable-mdpi/common_signin_btn_icon_normal_dark.9.png: Error: com.android.ide.common.process.ProcessException: 
[error] Total time: 4 s, completed 10-Oct-2015 21:37:36

**Comment by heiybb** [comment]
i just search the issues find that java1.8 is not support ...i would try to use jdk7 to build again,thanks

**Comment by Mygod** [comment]
Using Java 1.8 is fine now. I've been using that to build the project.

According to log, you might be trying to run 32-bit aapt on 64-bit Linux.
You should install 32-bit dependencies if that's the case.

**Comment by heiybb** [comment]
Accoirding to you advice,problem solved.
On Ubuntu Ubuntu 14.04.3 LTS  x64 it was enough to execute the following
sudo apt-get install libc6:i386 libstdc++6:i386
sudo apt-get install zlib1g:i386
