### ISSUE TITLE
最新版国行S6 5.1.1闪退

### ISSUE THREAD

**Issue by deepller** [shadowsocks/shadowsocks-android#444]
最新版国行S6 5.1.1闪退，请修复

**Comment by deepller** [comment]
已解决，需要卸载重新安装

**Comment by Mygod** [comment]
P.S. Please attach a logcat next time for debugging purposes.

**Comment by madeye** [comment]
```
E/AndroidRuntime(24700): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
E/AndroidRuntime(24700): 	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:239)
E/AndroidRuntime(24700): 	at android.preference.Preference.getPersistedInt(Preference.java:1621)
E/AndroidRuntime(24700): 	at com.github.shadowsocks.preferences.NumberPickerPreference.onSetInitialValue(NumberPickerPreference.scala:53)
E/AndroidRuntime(24700): 	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1438)
E/AndroidRuntime(24700): 	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1233)
E/AndroidRuntime(24700): 	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:167)
E/AndroidRuntime(24700): 	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:108)
E/AndroidRuntime(24700): 	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:45)
E/AndroidRuntime(24700): 	at android.preference.GenericInflater.rInflate(GenericInflater.java:488)
E/AndroidRuntime(24700): 	at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
E/AndroidRuntime(24700): 	at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/AndroidRuntime(24700): 	at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/AndroidRuntime(24700): 	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
E/AndroidRuntime(24700): 	at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:299)
E/AndroidRuntime(24700): 	at com.github.shadowsocks.ShadowsocksSettings.onCreate(ShadowsocksSettings.scala:21)
E/AndroidRuntime(24700): 	at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime(24700): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime(24700): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
E/AndroidRuntime(24700): 	at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1147)
E/AndroidRuntime(24700): 	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2116)
E/AndroidRuntime(24700): 	at android.app.Activity.onCreateView(Activity.java:5426)
E/AndroidRuntime(24700): 	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34)
```

**Comment by Mygod** [comment]
That's weird. I thought I've fixed that...

**Comment by Mygod** [comment]
Well I think I reintroduced the issue in this commit: https://github.com/shadowsocks/shadowsocks-android/commit/42c5a01d3e4035c4adc27e364806d4211cd67056

**Comment by Mygod** [comment]
I'm currently busy so you can fix this if you have time.

**Comment by madeye** [comment]
OK

**Comment by deepller** [comment]
还是会闪退，重装没用

**Comment by Mygod** [comment]
@deepller 请提供系统版本，logcat 等。

**Comment by deepller** [comment]
![140858841193279362](https://cloud.githubusercontent.com/assets/6301293/11360944/0e761f82-92c4-11e5-80ce-25bd380ac27c.jpg)
