### ISSUE TITLE
sbt build error:jarsigner Invalid keystore format

### ISSUE THREAD

**Issue by huwsun** [shadowsocks/shadowsocks-android#485]
When i build the app from source on my mac os 10.11
sbt failed because following error:
jarsigner error: java.lang.RuntimeException: keystore load: Invalid keystore format
java.lang.RuntimeException: Error signing jar (exit code was 1.)
	at scala.sys.package$.error(package.scala:27)
	at sbt.SignJar$.execute(Pack.scala:69)
	at sbt.SignJar$.sign(Pack.scala:59)
	at android.Tasks$$anonfun$52$$anonfun$apply$57.apply(tasks.scala:673)
	at android.Tasks$$anonfun$52$$anonfun$apply$57.apply(tasks.scala:663)
	at scala.Option.map(Option.scala:145)
	at android.Tasks$$anonfun$52.apply(tasks.scala:663)
	at android.Tasks$$anonfun$52.apply(tasks.scala:657)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (android:signRelease) Error signing jar (exit code was 1.)
[error] Total time: 43 s, completed Dec 22, 2015 4:37:24 PM

but i can manually  sign the apk successful:
jarsigner -verbose -keystore ~/.keystore shadowsocks-release-unsigned.apk polusAndroidKey

/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/23.0.2/zipalign -v 4 shadowsocks-release-unsigned.apk  shadowsocks.2.9.3.apk

so would you please help me to find out what gent wrong,I would be very grateful!

**Comment by madeye** [comment]
As said in your title, your keystore is invalid. Double check your keystore, make sure it's not corrupted.

**Comment by huwsun** [comment]
Thanks,i  found the problem:
keystore name must be same with the alias

**Comment by vocsyurvish** [comment]
I have issue as:

Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\admin\.android\debug.keystore": Invalid keystore format

##########################

i got this error in only older project.

if i create new project or leatest project i did't got any issue its work so good....

so how can i fixed this issue...
