### ISSUE TITLE
Can't connect if not owner in Multi-user mode

### ISSUE THREAD

**Issue by loxK** [shadowsocks/shadowsocks-android#557]
Android has the ability to configure multiple users. Shadowsocks will only connect when using the device as the owner and no other user can. The App looks in /data/data/com.github.shadowsocks/ whereas it should look in /data/user/<userID>/com.github.shadowsocks/

```
W/System.err(15424): java.io.FileNotFoundException: /data/data/com.github.shadowsocks/ss-local-vpn.conf: open failed: EACCES (Permission denied)
W/System.err(15424): 	at libcore.io.IoBridge.open(IoBridge.java:456)
W/System.err(15424): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
W/System.err(15424): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
W/System.err(15424): 	at java.io.PrintWriter.<init>(PrintWriter.java:127)
W/System.err(15424): 	at com.github.shadowsocks.utils.ConfigUtils$.printToFile(ConfigUtils.scala:189)
W/System.err(15424): 	at com.github.shadowsocks.ShadowsocksVpnService.startShadowsocksDaemon(ShadowsocksVpnService.scala:288)
W/System.err(15424): 	at com.github.shadowsocks.ShadowsocksVpnService.handleConnection(ShadowsocksVpnService.scala:252)
W/System.err(15424): 	at com.github.shadowsocks.ShadowsocksVpnService$$anonfun$startRunner$1.apply$mcV$sp(ShadowsocksVpnService.scala:239)
W/System.err(15424): 	at com.github.shadowsocks.ShadowsocksVpnService$$anonfun$startRunner$1.apply(ShadowsocksVpnService.scala:208)
W/System.err(15424): 	at com.github.shadowsocks.ShadowsocksVpnService$$anonfun$startRunner$1.apply(ShadowsocksVpnService.scala:208)
W/System.err(15424): 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
W/System.err(15424): 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
W/System.err(15424): 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
W/System.err(15424): 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
W/System.err(15424): 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
W/System.err(15424): 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
W/System.err(15424): 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
W/System.err(15424): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(15424): 	at libcore.io.Posix.open(Native Method)
W/System.err(15424): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/System.err(15424): 	at libcore.io.IoBridge.open(IoBridge.java:442)
W/System.err(15424): 	... 16 more
```

**Comment by madeye** [comment]
Fixed via d337f0e
