### ISSUE TITLE
[求助]关于编译源码的两个问题

### ISSUE THREAD

**Issue by houfukude** [shadowsocks/shadowsocks-android#618]
编译环境
>xubuntu 3.19.0-51-generic x86_64 GNU/Linux

sbtVersion
>[info] 0.13.11

在执行第三步：`sbt clean android:package-release`  
出现如下错误：

    [info] Loading project definition from ~/works/shadowsocks-android/project
    [info] Updating {file:~/works/shadowsocks-android/project/}shadowsocks-android-build...
    [info] Resolving com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT ...
    [warn] Unable to reparse com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT from Sonatype snapshots, using Sat Aug 02 02:50:30 CST 2014
    [warn] Choosing Sonatype snapshots for com.github.mpeltonen#sbt-idea;1.7.0-SNAPSHOT
    [info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435[info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    References to undefined settings: 

    android:packageBin::artifactPath from android:exportedProductsNoTracking (~/works/shadowsocks-android/build.sbt:3)

    android:packageBin::artifactPath from android:exportedProductsIfMissing (~/works/shadowsocks-android/build.sbt:3)
    
        at sbt.Init$class.Uninitialized(Settings.scala:270)
        at sbt.Def$.Uninitialized(Def.scala:10)
        at sbt.Init$class.delegate(Settings.scala:191)
        at sbt.Def$.delegate(Def.scala:10)
        at sbt.Init$class.compiled(Settings.scala:138)
        at sbt.Def$.compiled(Def.scala:10)
        at sbt.Init$class.make(Settings.scala:144)
        at sbt.Def$.make(Def.scala:10)
        at sbt.Load$.apply(Load.scala:145)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:54)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
    [error] References to undefined settings: 
    [error] 
    [error]   android:packageBin::artifactPath from android:exportedProductsNoTracking (~/works/shadowsocks-android/build.sbt:3)
    [error] 
    [error]   android:packageBin::artifactPath from android:exportedProductsIfMissing (~/works/shadowsocks-android/build.sbt:3)
    [error]  
    [error] Use 'last' for the full log.

完全无法定位错误的位置  
## Q1：纯命令行 应该如何定位错误呢？
是否与我现在的环境使用没有release的key有关？  
目前使用的是之前android studio默认的debugkey  
local.properties内容如下：  

    key.alias: androiddebugkey
    key.store: ~/.android/debug.keystore
    key.store.password: android
    ndk.dir=/opt/Android/Sdk/ndk-bundle
    sdk.dir=/opt/Android/Sdk/

@wllw 请教一下你是如何在android studio下编译ss的呢
目前使用的Android Stuido基本信息如下

    10:45:38,761 [   1608]  ERROR -    #com.intellij.lang.Language - Android Studio 1.5.1  Build #AI-141.2456560 
    10:45:38,762 [   1609]  ERROR -    #com.intellij.lang.Language - JDK: 1.8.0_65 
    10:45:38,762 [   1609]  ERROR -    #com.intellij.lang.Language - VM: Java HotSpot(TM) 64-Bit Server VM 
    10:45:38,762 [   1609]  ERROR -    #com.intellij.lang.Language - Vendor: Oracle Corporation 
    10:45:38,762 [   1609]  ERROR -    #com.intellij.lang.Language - OS: Linux 
    10:45:39,126 [   1973]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: [] 
    10:45:39,444 [   2291]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
    10:45:39,831 [   2678]   INFO -                  TestNG Runner - Create TestNG Template Configuration 
    10:45:39,941 [   2788]   INFO - ellij.project.impl.ProjectImpl - 26 project components initialized in 300 ms 
    10:45:39,941 [   2788]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
    10:45:41,416 [   4263]   INFO - pl.stores.ApplicationStoreImpl - 102 application components initialized in 3304 ms 
    10:45:41,419 [   4266]   INFO - .intellij.idea.IdeaApplication - App initialization took 4609 ms 
    10:45:42,511 [   5358]   INFO -                  TestNG Runner - Create TestNG Template Configuration 
    10:45:42,900 [   5747]   INFO - ellij.project.impl.ProjectImpl - 173 project components initialized in 782 ms 
    10:45:43,024 [   5871]   INFO - le.impl.ModuleManagerComponent - 2 module(s) loaded in 124 ms 
    10:45:44,204 [   7051]   INFO - tartup.impl.StartupManagerImpl - ~/works/shadowsocks-android/.idea/misc.xml case-sensitivity: true 
    10:45:44,425 [   7272]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  SBT) or icon jar:file:~/.AndroidStudio1.5/config/plugins/Scala/lib/scala-plugin.jar!/sbt.png 
    10:45:45,465 [   8312]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 3370 ms 
    10:45:46,270 [   9117]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 2520 ms 
    10:45:46,285 [   9132]   INFO -       #com.jetbrains.cidr.lang - Clearing symbols finished in 0 s. 
    10:45:46,286 [   9133]   INFO -       #com.jetbrains.cidr.lang - Loading symbols finished in 0 s. 
    10:45:46,293 [   9140]   INFO -       #com.jetbrains.cidr.lang - Building symbols finished in 0 s. 
    10:45:46,299 [   9146]   INFO -       #com.jetbrains.cidr.lang - Saving symbols finished in 0 s. 
    
在发现如上问题后尝试使用android studio导入项目
遇到如下问题：

    Error:Error while importing SBT project:
    ...
    [info] Resolving org.scala-sbt#tracking;0.13.5 ...
    [info] Resolving org.scala-sbt#cache;0.13.5 ...
    [info] Resolving org.scala-sbt#testing;0.13.5 ...
    [info] Resolving org.scala-sbt#test-agent;0.13.5 ...
    [info] Resolving org.scala-sbt#test-interface;1.0 ...
    [info] Resolving org.scala-sbt#main-settings;0.13.5 ...
    [info] Resolving org.scala-sbt#apply-macro;0.13.5 ...
    [info] Resolving org.scala-sbt#command;0.13.5 ...
    [info] Resolving org.scala-sbt#logic;0.13.5 ...
    [info] Resolving org.scala-sbt#compiler-interface;0.13.5 ...
    [info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.5 ...
    [info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.5 ...
    [info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.5 ...
    [info] Resolving org.scala-lang#jline;2.10.4 ...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    ~/works/shadowsocks-android/build.sbt:25: error: value jcenterRepo is not a member of object sbt.Resolver
    resolvers += Resolver.jcenterRepo
                        ^
    [error] Type error in expression

    See complete log in ~/.AndroidStudio1.5/system/log/sbt.last.log
    
尝试解决 修改 [build.sbt#L25](https://github.com/shadowsocks/shadowsocks-android/blob/master/build.sbt#L25) 为

>//resolvers += Resolver.jcenterRepo  
>resolvers += "jcenter" at "https://jcenter.bintray.com/"

能顺利更新依赖和导入，配置Run Configurations
![screenshot - 2016 03 23 - 11 35 27](https://cloud.githubusercontent.com/assets/3358382/13975008/092d5050-f0ec-11e5-9add-adc7758b4128.png)
后出现如下错误

    Error:(6, 14) Config is already defined as object Config
    public class Config implements Parcelable {
                ^
    Error:(6, 14) Config is already defined as class Config
    public class Config implements Parcelable {

    
然后通过修改配置 把项目作设置成为一个android项目
>Project -> Open Module Settings -> + -> Android

设置好Manifest file，res ，asset，Native，aidl后再次编译 出现如下问题：

    Information:Module "shadowsocks-android" was fully rebuilt due to project configuration/dependencies changes
    Information:16-3-23 上午11:26 - Compilation completed with 14 errors and 0 warnings in 3s 805ms
    ~/works/shadowsocks-android/src/main/res/values/styles.xml
    Error:(5, -1) android-apt-compiler: [shadowsocks-android] ~/works/shadowsocks-android/src/main/res/values/styles.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.Widget.AppCompat.Toolbar.Title'.
    Error:(8, -1) android-apt-compiler: [shadowsocks-android] ~/works/shadowsocks-android/src/main/res/values/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.
    Error:(12, -1) android-apt-compiler: [shadowsocks-android] ~/works/shadowsocks-android/src/main/res/values/styles.xml:12: error: Error: No resource found that matches the given name: attr 'colorAccent'.

**Comment by madeye** [comment]
Please post this kind of questions to forums or Q&A sites, e.g. v2ex, segmentfault.
