### ISSUE TITLE
2.10.2 nightly 强制关闭

### ISSUE THREAD

**Issue by ageback** [shadowsocks/shadowsocks-android#649]
老版本卸载后安装的官方版本，不是我自己编译的。
点击标题栏 Sahdowsocks\/ 程序就崩溃
android版本是 三星S5国行移动版（SM-G9008V），官方ROM 5.0.

**Comment by madeye** [comment]
```
D/AndroidRuntime( 2147): Shutting down VM
E/AndroidRuntime( 2147): FATAL EXCEPTION: main
E/AndroidRuntime( 2147): Process: com.github.shadowsocks, PID: 2147
E/AndroidRuntime( 2147): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.ProfileManagerActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class com.github.clans.fab.FloatingActionButton
E/AndroidRuntime( 2147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime( 2147): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime( 2147): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 2147): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 2147): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2147): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2147): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 2147): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2147): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 2147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 2147): Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class com.github.clans.fab.FloatingActionButton
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 2147): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
E/AndroidRuntime( 2147): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
E/AndroidRuntime( 2147): 	at com.github.shadowsocks.ProfileManagerActivity.onCreate(ProfileManagerActivity.scala:192)
E/AndroidRuntime( 2147): 	at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime( 2147): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 2147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime( 2147): 	... 10 more
E/AndroidRuntime( 2147): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2147): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 2147): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 2147): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime( 2147): 	... 23 more
E/AndroidRuntime( 2147): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_create.xml from drawable resource ID #0x7f02007d
E/AndroidRuntime( 2147): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2428)
E/AndroidRuntime( 2147): 	at android.content.res.Resources.loadDrawable(Resources.java:2330)
E/AndroidRuntime( 2147): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
E/AndroidRuntime( 2147): 	at android.widget.ImageView.<init>(ImageView.java:146)
E/AndroidRuntime( 2147): 	at android.widget.ImageButton.<init>(ImageButton.java:86)
E/AndroidRuntime( 2147): 	at android.widget.ImageButton.<init>(ImageButton.java:82)
E/AndroidRuntime( 2147): 	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:110)
E/AndroidRuntime( 2147): 	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:106)
E/AndroidRuntime( 2147): 	... 26 more
E/AndroidRuntime( 2147): Caused by: java.lang.NumberFormatException: Invalid float: "-.39.39"
E/AndroidRuntime( 2147): 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
E/AndroidRuntime( 2147): 	at java.lang.StringToReal.initialParse(StringToReal.java:160)
E/AndroidRuntime( 2147): 	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
E/AndroidRuntime( 2147): 	at java.lang.Float.parseFloat(Float.java:306)
E/AndroidRuntime( 2147): 	at android.util.PathParser.getFloats(PathParser.java:178)
E/AndroidRuntime( 2147): 	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
E/AndroidRuntime( 2147): 	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
E/AndroidRuntime( 2147): 	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
E/AndroidRuntime( 2147): 	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
E/AndroidRuntime( 2147): 	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
E/AndroidRuntime( 2147): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095
W/ActivityManager(  677):   Force finishing activity com.github.shadowsocks/.ProfileManagerActivity
W/ActivityManager(  677):   Force finishing activity com.github.shadowsocks/.Shadowsocks
```

Any thoughts? @Mygod

**Comment by CzBiX** [comment]
Google 提供的某些矢量资源无法在 5.0 上正常使用， 5.1 是正常的。
请注意使用新版本的资源文件。

**Comment by Mygod** [comment]
@CzBiX Really? More details?

**Comment by AnyOfYou** [comment]
I think this is not about resources file. Before I create #628 , I have tested it on device running Android 4.4.4.

**Comment by Mygod** [comment]
@AnyOfYou `VectorDrawable`s are only used in Android 5.0 or higher.

**Comment by CzBiX** [comment]
@Mygod 官方 repo issue: google/material-design-icons#176
我当时是让 5.0 系统使用 png 资源来解决的。
