### ISSUE TITLE
java.lang.NullPointerException?

### ISSUE THREAD

**Issue by winer632** [shadowsocks/shadowsocks-android#691]
[root@localhost shadowsocks-android]# sbt clean android:package-release
[info] Loading project definition from /home/wangxx/shadowsocks-android/project
[info] Set current project to shadowsocks (in build file:/home/wangxx/shadowsocks-android/)
[success] Total time: 0 s, completed May 23, 2016 9:11:58 AM
[info] Updating {file:/home/wangxx/shadowsocks-android/}shadowsocks-android...
[info] Resolving com.android.support#support-annotations;(19,) ...
[warn] File /root/.android/repositories.cfg could not be loaded.
[warn] UPDATE: A newer sbt-android is available: 1.6.2, currently running: 1.6.1
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Collecting resources
[info] Performing full resource merge
[warn] Errors during XML parse:
[warn] Additionally, the fallback loader failed to parse the XML.
[warn] Android SDK updates available, run 'android:update-sdk' to update:
[warn]     Android SDK Build-Tools 24-rc4
[warn]     Android Support Repository
[warn]     Google Repository
[warn]     Android SDK Tools 25.1.6
[warn]     Android SDK Platform-Tools 23.1
[info] Processing resources
[info] Rebuilding all classes because R.java has changed
[info] Compiling 40 Scala sources and 17 Java sources to /home/wangxx/shadowsocks-android/target/android/intermediates/classes...
[warn] there were three deprecation warnings; re-run with -deprecation for details
[warn] there were two feature warnings; re-run with -feature for details
[warn] two warnings found
java.lang.NullPointerException
        at com.android.tools.lint.checks.ApiClass.addAllFields(ApiClass.java:396)
        at com.android.tools.lint.checks.ApiClass.getAllFields(ApiClass.java:383)
        at com.android.tools.lint.checks.ApiLookup.writeDatabase(ApiLookup.java:412)
        at com.android.tools.lint.checks.ApiLookup.createCache(ApiLookup.java:237)
        at com.android.tools.lint.checks.ApiLookup.get(ApiLookup.java:209)
        at com.android.tools.lint.checks.ApiLookup.get(ApiLookup.java:132)
        at com.android.tools.lint.checks.ApiDetector.beforeCheckProject(ApiDetector.java:334)
        at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:901)
        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:436)
        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:377)
        at com.android.tools.lint.LintCliClient.run(LintCliClient.java:131)
        at android.AndroidLint$.apply(AndroidLint.scala:29)
        at android.Plugin$$anonfun$allPluginSettings$21.apply(rules.scala:189)
        at android.Plugin$$anonfun$allPluginSettings$21.apply(rules.scala:184)
        at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
        at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:compile) java.lang.NullPointerException
[error] Total time: 31 s, completed May 23, 2016 9:12:30 AM
[root@localhost shadowsocks-android]# 

[root@localhost shadowsocks-android]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core) 
[root@localhost shadowsocks-android]# 
[root@localhost shadowsocks-android]# java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
[root@localhost shadowsocks-android]#

**Comment by madeye** [comment]
Update your SDK or use a previous stable SDK.
