### ISSUE TITLE
ZTE Blade A1 闪退

### ISSUE THREAD

**Issue by jiangming1399** [shadowsocks/shadowsocks-android#768]
## 系统版本
5.1
## logcat

```
E/AndroidRuntime( 4759): FATAL EXCEPTION: main
E/AndroidRuntime( 4759): Process: com.github.shadowsocks, PID: 4759
E/AndroidRuntime( 4759): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}: android.view.InflateException: Binary XML file line #17: Error inflating class java.lang.reflect.Constructor
E/AndroidRuntime( 4759):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
E/AndroidRuntime( 4759):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
E/AndroidRuntime( 4759):        at android.app.ActivityThread.access$800(ActivityThread.java:178)
E/AndroidRuntime( 4759):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
E/AndroidRuntime( 4759):        at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 4759):        at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 4759):        at android.app.ActivityThread.main(ActivityThread.java:5644)
E/AndroidRuntime( 4759):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4759):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4759):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime( 4759):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 4759): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class java.lang.reflect.Constructor
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.createItem(GenericInflater.java:397)
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/AndroidRuntime( 4759):        at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/AndroidRuntime( 4759):        at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:281)
E/AndroidRuntime( 4759):        at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:324)
E/AndroidRuntime( 4759):        at com.github.shadowsocks.ShadowsocksSettings.onCreate(ShadowsocksSettings.scala:74)
E/AndroidRuntime( 4759):        at android.app.Fragment.performCreate(Fragment.java:2047)
E/AndroidRuntime( 4759):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:868)
E/AndroidRuntime( 4759):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1050)
E/AndroidRuntime( 4759):        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1152)
E/AndroidRuntime( 4759):        at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2142)
E/AndroidRuntime( 4759):        at android.app.Activity.onCreateView(Activity.java:5427)
E/AndroidRuntime( 4759):        at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36)
E/AndroidRuntime( 4759):        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:693)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(<Xposed>)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:693)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(<Xposed>)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 4759):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:693)
E/AndroidRuntime( 4759):        at android.view.LayoutInflater.inflate(<Xposed>)
E/AndroidRuntime( 4759):        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
E/AndroidRuntime( 4759):        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
E/AndroidRuntime( 4759):        at com.github.shadowsocks.Shadowsocks.onCreate(Shadowsocks.scala:324)
E/AndroidRuntime( 4759):        at android.app.Activity.performCreate(Activity.java:6100)
E/AndroidRuntime( 4759):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
E/AndroidRuntime( 4759):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
E/AndroidRuntime( 4759):        ... 11 more
E/AndroidRuntime( 4759): Caused by: java.lang.reflect.InvocationTargetException
W/ActivityManager(  900):   Force finishing activity 1 com.github.shadowsocks/.Shadowsocks
```

**Comment by madeye** [comment]
Disable your xposed.

**Comment by jiangming1399** [comment]
It still crash after I disable xposed.  Here are the logcat

```
E/AndroidRuntime( 5059): FATAL EXCEPTION: main
E/AndroidRuntime( 5059): Process: com.github.shadowsocks, PID: 5059
E/AndroidRuntime( 5059): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.shadowsocks/com.github.shadowsocks.Shadowsocks}: android.view.InflateException: Binary XML file line #17: Error inflating class java.lang.reflect.Constructor
E/AndroidRuntime( 5059):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
E/AndroidRuntime( 5059):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2614)
E/AndroidRuntime( 5059):        at android.app.ActivityThread.access$800(ActivityThread.java:178)
E/AndroidRuntime( 5059):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
E/AndroidRuntime( 5059):        at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 5059):        at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 5059):        at android.app.ActivityThread.main(ActivityThread.java:5644)
E/AndroidRuntime( 5059):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5059):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5059):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime( 5059):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime( 5059): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class java.lang.reflect.Constructor
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.createItem(GenericInflater.java:397)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/AndroidRuntime( 5059):        at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:281)
E/AndroidRuntime( 5059):        at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:324)
E/AndroidRuntime( 5059):        at com.github.shadowsocks.ShadowsocksSettings.onCreate(ShadowsocksSettings.scala:74)
E/AndroidRuntime( 5059):        at android.app.Fragment.performCreate(Fragment.java:2047)
E/AndroidRuntime( 5059):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:868)
E/AndroidRuntime( 5059):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1050)
E/AndroidRuntime( 5059):        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1152)
E/AndroidRuntime( 5059):        at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2142)
E/AndroidRuntime( 5059):        at android.app.Activity.onCreateView(Activity.java:5427)
E/AndroidRuntime( 5059):        at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36)
E/AndroidRuntime( 5059):        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
E/AndroidRuntime( 5059):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
E/AndroidRuntime( 5059):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 5059):        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 5059):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 5059):        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 5059):        at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
E/AndroidRuntime( 5059):        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
E/AndroidRuntime( 5059):        at com.github.shadowsocks.Shadowsocks.onCreate(Shadowsocks.scala:324)
E/AndroidRuntime( 5059):        at android.app.Activity.performCreate(Activity.java:6100)
E/AndroidRuntime( 5059):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
E/AndroidRuntime( 5059):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
E/AndroidRuntime( 5059):        ... 10 more
E/AndroidRuntime( 5059): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5059):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 5059):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 5059):        at android.preference.GenericInflater.createItem(GenericInflater.java:383)
E/AndroidRuntime( 5059):        ... 37 more
E/AndroidRuntime( 5059): Caused by: java.lang.VerifyError: Rejecting class android.widget.NumberPicker because it failed compile-time verification (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar)
E/AndroidRuntime( 5059):        at com.github.shadowsocks.preferences.NumberPickerPreference.<init>(NumberPickerPreference.scala:17)
E/AndroidRuntime( 5059):        ... 40 more
W/ActivityManager(  871):   Force finishing activity 1 com.github.shadowsocks/.Shadowsocks
```

**Comment by Mygod** [comment]
Uninstall and redownload.
