### ISSUE TITLE
306启用TCP fast open再开ss手机直接重启

### ISSUE THREAD

**Issue by baraja** [shadowsocks/shadowsocks-android#839]
安卓7.0@nexus 6p

**Comment by bubbless** [comment]
设备有root权限么？ TFO选项默认是打开的，我切换程序闪退。

**Comment by madeye** [comment]
@Mygod It seems very unstable to modify `/system`, what about using other methods?

**Comment by Mygod** [comment]
```
08-27 23:08:03.229  2727  2727 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.convert.Wrappers$JListWrapper.iterator(Wrappers.scala:88)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.AbstractTraversable.addString(Traversable.scala:104)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.AbstractTraversable.mkString(Traversable.scala:104)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:325)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at scala.collection.AbstractTraversable.mkString(Traversable.scala:104)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at com.github.shadowsocks.utils.TcpFastOpen$.enabled(TcpFastOpen.scala:49)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at com.github.shadowsocks.ShadowsocksSettings.com$github$shadowsocks$ShadowsocksSettings$$onPreferenceChange$body$16(ShadowsocksSettings.scala:162)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at com.github.shadowsocks.ShadowsocksSettings$$anonfun$17.onPreferenceChange(ShadowsocksSettings.scala:160)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.preference.Preference.callChangeListener(Preference.java:939)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:65)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:994)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3126)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4041)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-27 23:08:03.229  2727  2727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
My fault. This is not caused by modifying `/system` though.

**Comment by Mygod** [comment]
Please refrain from tapping on that button if you don't have root as this will solve this problem. On the other hand though, thanks for trying.

**Comment by baraja** [comment]
我有root权限的
