### ISSUE TITLE
Build error with go configuration

### ISSUE THREAD

**Issue by gongzelong** [shadowsocks/shadowsocks-android#948]
When I build the app, execute the command 
```
sbt native-build clean android:package-release
```

I installed the go with brew.

The go is located on */usr/local/Cellar/go/1.7.1*

```
ZelongdeMacBook-Pro:shadowsocks-android gongzelong$ sbt native-build clean android:package-release
[info] Loading project definition from /Users/gongzelong/Android/githubrepo/shadowsocks-android/project
[info] Set current project to shadowsocks (in build file:/Users/gongzelong/Android/githubrepo/shadowsocks-android/)
[info] ~/Android/githubrepo/shadowsocks-android/src/main ~/Android/githubrepo/shadowsocks-android
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[info] Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module sodium    
[info] Android NDK:   shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2-impl.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse2.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-load-sse41.h shadowsocks-libev/libsodium/src/libsodium/crypto_generichash/blake2/ref/blake2b-round.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h shadowsocks-libev/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h shadowsocks-libev/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/base2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/d2.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_add.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_madd.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_msub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/ge_sub.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow22523.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/pow225521.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sc.h shadowsocks-libev/libsodium/src/libsodium/crypto_sign/ed25519/ref10/sqrtm1.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.h shadowsocks-libev/libsodium/src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/curve25519_ref10.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/fe.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h shadowsocks-libev/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h    
[info] [armeabi-v7a] Install        : pdnsd => libs/armeabi-v7a/pdnsd
[info] [armeabi-v7a] Install        : redsocks => libs/armeabi-v7a/redsocks
[info] [armeabi-v7a] Install        : ss-local => libs/armeabi-v7a/ss-local
[info] [armeabi-v7a] Install        : ss-tunnel => libs/armeabi-v7a/ss-tunnel
[info] [armeabi-v7a] Install        : libsystem.so => libs/armeabi-v7a/libsystem.so
[info] [armeabi-v7a] Install        : tun2socks => libs/armeabi-v7a/tun2socks
[info] [x86] Install        : pdnsd => libs/x86/pdnsd
[info] [x86] Install        : redsocks => libs/x86/redsocks
[info] [x86] Install        : ss-local => libs/x86/ss-local
[info] [x86] Install        : ss-tunnel => libs/x86/ss-tunnel
[info] [x86] Install        : libsystem.so => libs/x86/libsystem.so
[info] [x86] Install        : tun2socks => libs/x86/tun2socks
[info] pdnsd
[info] redsocks
[info] ss-local
[info] ss-tunnel
[info] tun2socks
[info] ~/Android/githubrepo/shadowsocks-android
[info] ~/Android/githubrepo/shadowsocks-android/kcptun ~/Android/githubrepo/shadowsocks-android
[info] Build the custom go
[info] ~/Android/githubrepo/shadowsocks-android/kcptun/go/src ~/Android/githubrepo/shadowsocks-android/kcptun
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] warning: GOPATH set to GOROOT (/usr/local/Cellar/go/1.7.1) has no effect
[error] cmd/dist/build.go:8:2: cannot find package "bytes" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/bytes (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:9:2: cannot find package "encoding/json" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/encoding/json (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:9:2: cannot find package "errors" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/errors (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:10:2: cannot find package "flag" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/flag (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:11:2: cannot find package "fmt" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/fmt (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/util.go:10:2: cannot find package "io" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/io (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/util.go:11:2: cannot find package "io/ioutil" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/io/ioutil (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:12:2: cannot find package "log" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/log (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:12:2: cannot find package "os" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/os (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:13:2: cannot find package "os/exec" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/os/exec (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:14:2: cannot find package "path/filepath" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/path/filepath (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:16:2: cannot find package "regexp" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/regexp (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/util.go:15:2: cannot find package "runtime" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/runtime (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:15:2: cannot find package "sort" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/sort (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/main.go:11:2: cannot find package "strconv" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/strconv (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:16:2: cannot find package "strings" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/strings (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/build.go:17:2: cannot find package "sync" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/sync (from $GOROOT)
[error] 	($GOPATH not set)
[error] cmd/dist/test.go:20:2: cannot find package "time" in any of:
[error] 	/usr/local/Cellar/go/1.7.1/src/time (from $GOROOT)
[error] 	($GOPATH not set)
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $d9befcaba2dcd1551d45$$anonfun$$sbtdef$1.apply(/Users/gongzelong/Android/githubrepo/shadowsocks-android/build.sbt:57)
	at $d9befcaba2dcd1551d45$$anonfun$$sbtdef$1.apply(/Users/gongzelong/Android/githubrepo/shadowsocks-android/build.sbt:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeBuild) Native build script exit code: 255
[error] Total time: 1 s, completed Oct 22, 2016 5:44:16 PM
```

vim ~/.bash_profile

```
export ANDROID_HOME=/Users/gongzelong/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

export ANDROID_NDK_HOME=/Users/gongzelong/Library/Android/ndk
#ANDROID_NDK_HOME bin
export PATH=$ANDROID_NDK_HOME:$PATH
#export PATH=${PATH}:$ANDROID_NDK_HOME

export GOPATH=/usr/local/Cellar/go/1.7.1
export PATH=$GOPATH/bin:$PATH

export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

export GOROOT_BOOTSTRAP=$GOPATH
export PATH=$PATH:$GOROOT_BOOTSTRAP

export GOROOT=$GOPATH
export PATH=$PATH:$GOROOT/bin
```

I searched a lot and tried several times.
Could you plz help me to fix this. Appreciated ahead.

**Comment by gongzelong** [comment]
```
go env
```
```
ZelongdeMacBook-Pro:~ gongzelong$ go env
warning: GOPATH set to GOROOT (/usr/local/Cellar/go/1.7.1) has no effect
GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/1.7.1/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/Cellar/go/1.7.1"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gf/hgd91n6x5v73ct9dvhr379500000gn/T/go-build226880260=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
I use MacOS and terminal. I should use bash shell terminal to execute all the commands.

**Comment by gongzelong** [comment]
I revise the ~/.bash_profile like below.

```
xport ANDROID_HOME=/Users/gongzelong/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

export ANDROID_NDK_HOME=/Users/gongzelong/Library/Android/ndk
#ANDROID_NDK_HOME bin
export PATH=$ANDROID_NDK_HOME:$PATH
#export PATH=${PATH}:$ANDROID_NDK_HOME

export GOPATH=/usr/local/Cellar/go/1.7.1/libexec
export PATH=$GOPATH/bin:$PATH

export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

export GOROOT_BOOTSTRAP=/usr/local/Cellar/go/1.7.1
export PATH=$PATH:$GOROOT_BOOTSTRAP

export GOROOT=$GOPATH
export PATH=$PATH:$GOROOT/bin
```

And then I execute the command 

```
sbt native-build clean android:package-release
```
I got this.

```
[info] ##### Building Go bootstrap tool.
[info] cmd/dist
[error] import cycle not allowed
[error] package ./cmd/dist
[error] 	imports bytes
[error] 	imports errors
[error] 	imports runtime
[error] 	imports runtime/internal/atomic
[error] 	imports unsafe
[error] 	imports runtime
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $d9befcaba2dcd1551d45$$anonfun$$sbtdef$1.apply(/Users/gongzelong/Android/githubrepo/shadowsocks-android/build.sbt:57)
	at $d9befcaba2dcd1551d45$$anonfun$$sbtdef$1.apply(/Users/gongzelong/Android/githubrepo/shadowsocks-android/build.sbt:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeBuild) Native build script exit code: 255
[error] Total time: 1 s, completed Oct 22, 2016 6:18:51 PM
```

**Comment by madeye** [comment]
`export GOROOT_BOOTSTRAP=/usr/local/Cellar/go/1.7.1/libexec`

**Comment by gongzelong** [comment]
Resolved. Thanks a lot.

**Comment by gongzelong0718** [comment]
Marked
