### ISSUE TITLE
where is pcre @ 222bbf4 git link?

### ISSUE THREAD

**Issue by feikai2012** [shadowsocks/shadowsocks-android#958]
where is pcre @ 222bbf4 git link?
Can I use this android-ndk32-r10b to compile it?
this is error log

[error] make: *** No rule to make target `jni/pcre/dist/pcre_byte_order.c', needed by `obj/local/armeabi-v7a/objs/pcre/pcre/dist/pcre_byte_order.o'.  Stop.
[error] make: *** Waiting for unfinished jobs....
java.lang.RuntimeException: Native build script exit code: 255
	at scala.sys.package$.error(package.scala:27)
	at $bd7db39e194222eb512b$$anonfun$$sbtdef$1.apply(/home/jones/shadowsocksr-android/build.sbt:57)
	at $bd7db39e194222eb512b$$anonfun$$sbtdef$1.apply(/home/jones/shadowsocksr-android/build.sbt:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:nativeBuild) Native build script exit code: 255
[error] Total time: 1 s, completed 2016-10-27 11:52:45

**Comment by madeye** [comment]
`git submodule update --init`
