### ISSUE TITLE
编译过程当中提示不是有效的32位应用 如何解决

### ISSUE THREAD

**Issue by 1107470624** [shadowsocks/shadowsocks-android#980]
Please read FAQ in wiki then answer these questions before submitting your issue. Thanks!

### Environment

* Android version: *e.g. "7.0.0_r14", more detailed description is preferred*
* Device: *e.g. Google Pixel XL*
* Shadowsocks version: *version code "v3.0.0" or commit ID "a073f85"*
* Last version that did not exhibit the issue (if applicable):

### Configuration

_Put an `x` inside the [ ] that applies._

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method:
* [ ] One-time authentication
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [ ] UDP Forwarding
* KCP Parameters: (leave blank if not enabled)
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

**Comment by Mygod** [comment]
Since it's an issue related to compilation, you should attach the full compilation log.

**Comment by Mygod** [comment]
Closed due to inactivity.

**Comment by AndlsH** [comment]
```
Z:\shadowsocks-android> sbt native-build clean android:package-release
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[info] Loading project definition from Z:\shadowsocks-android\project
[info] Set current project to shadowsocks (in build file:/Z:/shadowsocks-android/)
java.io.IOException: Cannot run program "./build.sh": CreateProcess error=193, %1 不是有效的 Win32 应用程序。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
        at $e41ade57fd503bf22ce5$$anonfun$$sbtdef$1.apply(Z:\shadowsocks-android\build.sbt:55)
        at $e41ade57fd503bf22ce5$$anonfun$$sbtdef$1.apply(Z:\shadowsocks-android\build.sbt:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=193, %1 不是有效的 Win32 应用程序。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
        at $e41ade57fd503bf22ce5$$anonfun$$sbtdef$1.apply(Z:\shadowsocks-android\build.sbt:55)
        at $e41ade57fd503bf22ce5$$anonfun$$sbtdef$1.apply(Z:\shadowsocks-android\build.sbt:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:nativeBuild) java.io.IOException: Cannot run program "./build.sh": CreateProcess error=193, %1 不是有效的 Win32 应用程序。
[error] Total time: 0 s, completed 2016-11-21 17:41:43
```

**Comment by 1107470624** [comment]
遇到的情况和你的一样 请问您是如何解决的 或者有高手来解决？

**Comment by 1107470624** [comment]
@AndlsH 和您一样遇到这样的问题 请问您是怎么解决的 ？或者说有高手告诉下如何解决

**Comment by Mygod** [comment]
@AndlsH @1107470624 This project can't be built under Windows yet. A pull request is welcome.
