### ISSUE TITLE
编译过程中出现%1 不是有效的 Win32 应用程序

### ISSUE THREAD

**Issue by wydewy** [shadowsocks/shadowsocks-android#994]
$ sbt native-build clean android:package-release
[info] Loading project definition from F:\Android\project\shadowsocks-android\project
[info] Set current project to shadowsocks (in build file:/F:/Android/project/shadowsocks-android/)
java.io.IOException: Cannot run program "./build.sh": CreateProcess error=193, %1 ²»ÊÇÓÐÐ§µÄ Win32 Ó¦ÓÃ³ÌÐò¡£
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
        at $d4d2e819913ae0628d6e$$anonfun$$sbtdef$1.apply(F:\Android\project\shadowsocks-android\build.sbt:55)
        at $d4d2e819913ae0628d6e$$anonfun$$sbtdef$1.apply(F:\Android\project\shadowsocks-android\build.sbt:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=193, %1 ²»ÊÇÓÐÐ§µÄ Win32 Ó¦ÓÃ³ÌÐò¡£
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
        at $d4d2e819913ae0628d6e$$anonfun$$sbtdef$1.apply(F:\Android\project\shadowsocks-android\build.sbt:55)
        at $d4d2e819913ae0628d6e$$anonfun$$sbtdef$1.apply(F:\Android\project\shadowsocks-android\build.sbt:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:nativeBuild) java.io.IOException: Cannot run program "./build.sh": CreateProcess error=193, %1 不是有效的 Win32 应用程序
[error] Total time: 0 s, completed 2016-12-3 8:44:54
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

**Comment by madeye** [comment]
You can't build this project on Windows.

Follow the README to build it on a *inx system or try bash on Windows 10.
